### PR TITLE
scopatz emeritus

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
:(

**Comment by scopatz** [comment]
Yeah - I am sorry, I have been thinking of doing this for a while.  I definitely need a forced break for my own mental health and to some space to work on other things, like the xonsh and the conda community. I'll come back whenever the time is right.

**Comment by beckermr** [comment]
I support you! Just expressing my sadness. :(

**Comment by scopatz** [comment]
Happy to chat out of bounds too.

**Pull request merged**
