### PR TITLE
Add an index of CFEPs

### LINKED ISSUE #1241: Add index of CFEPs
I think it would be nice to have an index of CFEPs in the main documentation.

Even when the main content of a CFEP has been included in the docs, CFEPs provide useful information. They are not very easy to find today. An index would ease that.
It would be good if this was automated but I don't really see how it would fit with the sphinx documentation. On the other side, there aren't that many CFEPs. Updating the index manually should be fine.

If there is interest, I could make a PR.

### PR DESCRIPTION
**Pull request by beenje**
Fix #1241 

Note that the index needs to be maintained and updated manually.

### CODE REVIEW

**Review by beckermr — COMMENTED** [review]
Can we generate this list automatically from the CFEP repo?

**Comment by beenje** [comment]
Will try to propose a small script!

**Comment by beenje** [comment]
I added a script that should append the list of CFEPs automatically to the `cfep-index.rst` file.

**Comment by jakirkham** [comment]
Thank you for all of these doc improvements! 😄

**Pull request merged**
