### PR TITLE
Fix the rendering of markdown text between backsticks in the incidents titles

### PR DESCRIPTION
**Pull request by HaudinFlorence**
PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] if you are adding a new page under `docs/` or `community/`, you have added it to the sidebar in the corresponding `_sidebar.json` file
- [ ] put any other relevant information below

This PR aimed at fixing task 5 of issue #2137 mentioning that in incidents titles, the text elements between backsticks were not rendered in markdown style.

### CODE REVIEW

**Comment by jaimergp** [comment]
Thanks @HaudinFlorence. Is there a chance we can use that component to also render the plain URLs into clickable ones? i.e. https://github.com/conda-forge/conda-forge.github.io/issues/2181

**Comment by HaudinFlorence** [comment]
> Thanks @HaudinFlorence. Is there a chance we can use that component to also render the plain URLs into clickable ones? i.e. #2181

**Comment by HaudinFlorence** [comment]
> > Thanks @HaudinFlorence. Is there a chance we can use that component to also render the plain URLs into clickable ones? i.e. #2181

@jaimergp I think it can be used but I am not sure how since it seems if I see correctly that Github urls are only given as simple text in `issue.body` and not as link.

**Comment by jaimergp** [comment]
I'm not sure which Markdown component we are using there exactly, but we do have [`remark-gfm`](https://github.com/remarkjs/remark-gfm) in the lockfile already, so it we can leverage that, then it should work? But we can do that in another PR if you prefer smaller scopes.

**Comment by HaudinFlorence** [comment]
> Since we are using `react-markdown` and already have [`remark-gfm`](https://github.com/remarkjs/remark-gfm) in the lockfile, we can use it as a plugin I think?
> 
> See this example from [`react-markdown`](https://github.com/remarkjs/react-markdown?tab=readme-ov-file):
> 
> ```js
> import React from 'react'
> import {createRoot} from 'react-dom/client'
> import Markdown from 'react-markdown'
> import remarkGfm from 'remark-gfm'
> 
> const markdown = `Just a link: www.nasa.gov.`
> 
> createRoot(document.body).render(
>   <Markdown remarkPlugins={[remarkGfm]}>{markdown}</Markdown>
> )
> ```

Thanks for the pointer. It works. I will open a specific PR to fix issue https://github.com/conda-forge/conda-forge.github.io/issues/2181

**Comment by HaudinFlorence** [comment]
@jaimergp I am don't know how to fix the check link failing test. If you have any hint please? Thanks.

**Comment by jaimergp** [comment]
We will need to either ignore link checks in anaconda.org/conda-forge or increase the timeouts, but don't worry for now.

**Comment by jaimergp** [comment]
Added https://github.com/conda-forge/conda-forge.github.io/pull/2231

**Pull request merged**
