### PR TITLE
Document how to manually migrate a feedstock

### PR DESCRIPTION
**Pull request by jakirkham**
In some cases a migration may not go smoothly, this provides documentation on how to check the status, what to do in different cases (including where to raise issues if needed), and how to perform the migration manually if necessary. Hopefully this also provide a better idea of what is going on behind the current with migrations for those less familiar with conda-forge's infrastructure, who occasionally need to apply a migration.

<hr>

PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

### CODE REVIEW

**Comment by jakirkham** [comment]
Screen Shot 2022-12-12 at 2 17 52 PM

**Comment by jakirkham** [comment]
Screen Shot 2022-12-12 at 2 18 34 PM

**Comment by beckermr** [comment]
Ready to merge?

**Comment by jakirkham** [comment]
If it looks ok to you. It is good on my end

**Pull request merged**
