### PR TITLE
Pin librdkafka

### PR DESCRIPTION
**Pull request by mrocklin**
As requested in: https://github.com/conda-forge/staged-recipes/pull/4091#discussion_r143362793

[API/ABI report]( https://abi-laboratory.pro/tracker/timeline/librdkafka/ )

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
cc @conda-forge/librdkafka

**Comment by jakirkham** [comment]
LGTM

**Comment by mrocklin** [comment]
Anything left to do here?

**Comment by isuruf** [comment]
ping @conda-forge/librdkafka

**Comment by mrocklin** [comment]
Note that @jakirkham already pinged librdkafka yesterday

**Comment by jakirkham** [comment]
Let's go ahead with this.

It sounds like @kwilcox was [on board]( https://github.com/conda-forge/staged-recipes/pull/4091#discussion_r142048433 ). Just wanted to double check/raise awareness. If that turns out not to be the case or there is some other issue that crops up, we can always discuss and update accordingly.

Thanks @mrocklin!

**Pull request merged**
