### PR TITLE
Migrate blog to Docusaurus

### PR DESCRIPTION
**Pull request by jaimergp**
PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

More of #1971. To check locally:

```
conda env create -n conda-forge-docusaurus -f .ci_scripts/environment.yml
conda activate conda-forge-docusaurus
npm run build
python -m http.server -d build
```

We will need to archive `conda-forge/blog` after disabling its GH Pages integrations.

### CODE REVIEW

**Comment by jaimergp** [comment]
A live preview is available at https://cf-infra-docs.netlify.app/blog/, but without all the compatibility redirects.

**Comment by beckermr** [comment]
So we've moved the blog entries here? That's fine. Do the old links work properly? Cc @isuruf who had an issue with this years ago.

**Comment by beckermr** [comment]
Sorry let me be more specific. There was an old set of redirects built into the current blog from an even older version. Did you get those?

**Comment by jaimergp** [comment]
@beckermr - I checked and I had covered the redirects already, I just didn't remember hah. The main point is that Docusaurus implements the URL schema that the `conda-forge/blog` system was redirecting. There only a couple instances where it doesn't match (e.g. [this one](https://github.com/conda-forge/conda-forge.github.io/pull/2054/files?diff=split&w=0#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2aR180)), and in those cases we are covering it now. What we did need to do was to redirect the dashed dates to slash dates in the existing posts.

**Review by beckermr — APPROVED** [review]

**Comment by jaimergp** [comment]
cc @jakirkham

**Review by jezdez — APPROVED** [review]

**Comment by beckermr** [comment]
I'll start taking apart the old blog later today and then merge this one.

**Comment by beckermr** [comment]
all steps done - blog should be back up in new site in a few minutes

**Comment by jaimergp** [comment]
Yay, here it is: https://conda-forge.org/blog/

Thanks everyone!

**Pull request merged**
