### PR TITLE
Fix dependency matching with regex

### PR DESCRIPTION
**Pull request by krischer**
See https://github.com/conda-forge/conda-forge.github.io/pull/255

This is totally untested as I did not run it. But the principle should be correct.

### CODE REVIEW

**Comment by krischer** [comment]
This also has the advantage that it does not touch already pinned dependencies.

**Comment by krischer** [comment]
There still might be an issue if the is no space between the '-' and the actual dependency name. But I guess your linter guarantees that in any case.

**Comment by astaric** [comment]
I have managed to run the code with proposed fix. It does not suggest to pin package pyqtgraph anymore, which is an improvement (it used to, because it started with pyqt, which is pinned).

The missing space between - and dependency name results in yaml parses error on my machine, so it should not be a problem.

+1 for merge

**Comment by pelson** [comment]
Awesome. Thanks @krischer & @astaric. 👍

**Pull request merged**
