### PR TITLE
DOC: Add travis badge to readme

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM. Not sure if there was a reason we hadn't included this. So, am going to let it sit for a bit.

**Comment by jakirkham** [comment]
Not hearing any complaints. Let's do it. Thanks @ericdill.

**Comment by ericdill** [comment]
Thanks @jakirkham . This will make it much simpler to detect if travis is failing. Speaking of which, why is travis failing? Oh. github rate limiting...

**Comment by ocefpaf** [comment]
+1
Em 26/05/2016 16:45, "Eric Dill" <notifications@github.com> escreveu:

**Comment by jakirkham** [comment]
> Speaking of which, why is travis failing? Oh. github rate limiting...

Yeah, I put it on the hackpad again. Basically the team addition script needs close review. It is tricky to make this efficient without losing something though.

**Pull request merged**
