### PR TITLE
Add meeting notes action

### PR DESCRIPTION
**Pull request by jaimergp**
PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [X] put any other relevant information below

Same as https://github.com/conda-incubator/governance/pull/88

### CODE REVIEW

**Comment by jaimergp** [comment]
Looks like the conda docs have been rearranged :(

**Comment by jaimergp** [comment]
It's like the [`latest` version](https://docs.conda.io/projects/conda/en/latest) does not work anymore. `stable` is ok though.

**Comment by jaimergp** [comment]
That did it  🙌

**Comment by jakirkham** [comment]
So what do we need to do to add the meeting notes from this week?

**Comment by beckermr** [comment]
Those will have to be added by hand.

**Comment by jakirkham** [comment]
Thanks! Makes sense. Submitted PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1912 )

Maybe this is a good time to figure out what we do for the next meeting? (cc @ericdill)

**Pull request merged**
