### PR TITLE
link added in the to-do list (issue  #1314 )

### PR DESCRIPTION
**Pull request by prachi237**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs`
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
This link is wrong and idk exactly what this or is trying to fix.

**Comment by prachi237** [comment]
> This link is wrong and idk exactly what this or is trying to fix.

In the Miscellaneous section of Conda-forge documentation https://conda-forge.org/docs/misc/00_intro.html#term-abi
ain't the link is invalid, ?

Screenshot (91)_LI

**Comment by beckermr** [comment]
That is a path to the a file that exists on the ci system.

**Comment by prachi237** [comment]
> That is a path to the a file that exists on the ci system.

yes sir I added the link of the page from where the address can be accessed  which is present is ``.src`` file, if it's not gng to help, I'll close the issue.

**Comment by beckermr** [comment]
Ah you are correct! Sorry! Lgtm!

**Pull request merged**
