### PR TITLE
Update add maintainer bot title

### PR DESCRIPTION
**Pull request by kbrindley**
PR Checklist:

- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

I didn't find any relevant PRs with the search text "conda-forge-admin".

With the comma, my Issue sat for 3 days. Without the comma, my issue was addressed immediately by ``conda-forge-admin``.

https://github.com/conda-forge/waves-feedstock/issues/2

### CODE REVIEW

**Comment by beckermr** [comment]
This is a bug in the webservices code actually.

**Comment by kbrindley** [comment]
The closest issue in the conda-forge-webservices repo that I could find is this one: https://github.com/conda-forge/conda-forge-webservices/issues/474. It's not clear to me if the linked issue's scope overlaps with the behavior in this PR.

1. Is it worth updating the documentation to match existing behavior while the patch is pending?
2. Would you like for me to open a new issue in https://github.com/conda-forge/conda-forge-webservices?

I'm happy to close the PR if you prefer.

Thanks!

**Comment by beckermr** [comment]
Yes please do open an issue in the webservices code base. My guess is that our regex is broken.

**Comment by kbrindley** [comment]
I opened an issue here: https://github.com/conda-forge/conda-forge-webservices/issues/530.

**Comment by jakirkham** [comment]
Should we close this PR?

**Comment by beckermr** [comment]
This appears to have fixed itself and IDK why. Let's close for now.

**Pull request closed without merging**
