### PR TITLE
Updating the Build Procedure in README.md  #1305

### PR DESCRIPTION
**Pull request by prachi237**

### CODE REVIEW

**Comment by prachi237** [comment]
@viniciusdc  I  have send a new PR this time, last time 270 files got changes even I don't know how that happened🤐

**Comment by viniciusdc** [comment]
> @viniciusdc I have send a new PR this time, last time 270 files got changes even I don't know how that happened

no worries, thanks for the new PR (probably it was the merge you did or some local build of the docs :))

**Comment by viniciusdc** [comment]
LGTM. THought, haven't you forgotten this line "To build the docs locally, you should follow the steps mentioned below:" ?

**Comment by viniciusdc** [comment]
close #1305

**Comment by prachi237** [comment]
> LGTM. Though, haven't you forgotten this line "To build the docs locally, you should follow the steps mentioned below:" ?



> LGTM. Though, haven't you forgotten this line "To build the docs locally, you should follow the steps mentioned below:" ?
 
I had mentioned that  step by step process to get started with sphinx previously (I provided the link as well)  @marscher  told me that was not needed so I deleted that.

**Comment by viniciusdc** [comment]
> > LGTM. Though, haven't you forgotten this line "To build the docs locally, you should follow the steps mentioned below:" ?
> > 
> I had mentioned that step by step process to get started with sphinx previously (I provided the link as well) @beckermr told me that was not needed so I deleted that.

Yes indeed, I saw that discussion and agree with Matt comment there. But I was just saying that in you last PR (the closed one) you change the line 14 too (you corrected some typos there)

**Review by viniciusdc — COMMENTED** [review]
LGTM

**Comment by prachi237** [comment]
> > > LGTM. Though, haven't you forgotten this line "To build the docs locally, you should follow the steps mentioned below:" ?
> > 
> > 
> > I had mentioned that step by step process to get started with sphinx previously (I provided the link as well) @beckermr told me that was not needed so I deleted that.
> 
> Yes indeed, I saw that discussion and agree with Matt. But I was just saying that in you last PR (the closed one) you also changde the line 14 too (you corrected some typos there)

sorry sir, my bad I only added the lines, forgot to change the previous file that's why this happened, hope now every thing works well.

**Pull request closed without merging**
