### PR TITLE
Adding nettle pinning

### PR DESCRIPTION
**Pull request by Cashalow**
Following https://github.com/conda-forge/staged-recipes/pull/3884#discussion_r137950866 I am updating this file for nettle pinning.

ABI report: https://abi-laboratory.pro/tracker/timeline/nettle/

### CODE REVIEW

**Comment by dougalsutherland** [comment]
It looks like:
- `nettle` isn't in defaults, so the comment should be `NA` instead of `3.3.0`.
- The version number is actually `3.3`, not `3.3.0`, so the pin should be `3.3|3.3.*`.

**Comment by Cashalow** [comment]
Ok thanks for the input !

**Comment by jakirkham** [comment]
Added a link to the ABI report in the OP.

**Comment by jakirkham** [comment]
Thanks @Cashalow and @dougalsutherland.

**Pull request merged**
