### PR TITLE
 Update errored version updates version formatting

### PR DESCRIPTION
**Pull request by HaudinFlorence**
PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] if you are adding a new page under `docs/` or `community/`, you have added it to the sidebar in the corresponding `_sidebar.json` file
- [ ] put any other relevant information below

This PR aims at fixing task 11 of issue https://github.com/conda-forge/conda-forge.github.io/issues/2137
For the errored version updates, it replaces `<pre>` by `<Markdown>` components with relevant properties.

### CODE REVIEW

**Comment by HaudinFlorence** [comment]
I am not sure whether `<a href="https://github.com/...">bot CI job</a>` should be parse in the error message.

**Comment by jaimergp** [comment]
Probably, yes. But we should fix how the bot emits these errors so it's a better looking Markdown. We could also [process](https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown) the HTML-in-Markdown thingy, but that's a bit too much?

Let me see if I can find how we emit these error blobs.

**Comment by jaimergp** [comment]
cc @beckermr  - we are looking at prettifying the version update errors.

From:

image

To:

image


For best results, we might need to adjust this [blob](https://github.com/regro/cf-scripts/blob/98f3ea00203e7a7d33d43e1d6c791e2227d778f1/conda_forge_tick/auto_tick.py#L648-L659) in cf-scripts. Any thoughts?

**Comment by beckermr** [comment]
Yes this has been on my todo list and I agree. Let's merge the pr here and we can merge a change in the bot. Unfortunately we may have to go back and edit the existing blobs to make everything look nice.

**Comment by jaimergp** [comment]
I see two ways to do this:

- Make the bot generate markdown. This PR would be sufficient.
- Make the bot generate JSON payloads. We would need to parse the JSON a bit here before merging. I imagine a schema like:

```js
{
  "status": str,  // I guess we only have 'error' here?
  "n_attempts": int,
  "job_url": str,
  "branch": str,
  "message": str
}
```

I think long term JSON makes more sense but I don't know how tricky that would be. WDYT?

**Comment by beckermr** [comment]
What do we do for the migration errors? We should follow that maybe?

**Comment by beckermr** [comment]
@jaimergp for the version updates, we need to adjust this line: https://github.com/regro/cf-scripts/blob/98f3ea00203e7a7d33d43e1d6c791e2227d778f1/conda_forge_tick/auto_tick.py#L632 The one you linked is for plain migrators.

**Comment by beckermr** [comment]
Oh weird, now I see both things in both places.

**Comment by beckermr** [comment]
OK see this PR: https://github.com/conda-forge/conda-forge.github.io/pull/2234

**Comment by jaimergp** [comment]
Thanks @HaudinFlorence. Closing this one in favor of https://github.com/conda-forge/conda-forge.github.io/pull/2234. We might revisit this section of the status page in the future, though. I'll keep you posted!

**Comment by HaudinFlorence** [comment]
> Thanks @HaudinFlorence. Closing this one in favor of #2234. We might revisit this section of the status page in the future, though. I'll keep you posted!

@jaimergp Ok. Thanks for the input.

**Pull request closed without merging**
