### PR TITLE
pin arpack

### PR DESCRIPTION
**Pull request by dougalsutherland**
This is just to the latest major.minor version, not sure about ABI compatibility.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please ask them to add it [here]( https://github.com/lvc/upstream-tracker/issues ). They are usually quite prompt. Also cc @jschueller.

**Comment by dougalsutherland** [comment]
[Looks like](https://abi-laboratory.pro/tracker/timeline/arpack-ng/) arpack was pretty much stable 3.4 to 3.5, but broke 3.3 to 3.4.

**Comment by jakirkham** [comment]
Thoughts @jschueller?

**Comment by jakirkham** [comment]
Ack! Sorry. Merged a bunch of stuff and it seems like this now conflicts. Could you please fix the merge conflict. Hopefully it is straightforward.

**Comment by dougalsutherland** [comment]
Rebased. (It was just git being confused by the adjacent change to boost.)

**Comment by jakirkham** [comment]
Looks like this has conflicts again. Before we fix them though, are you ok with this pinning @jschueller?

**Comment by dougalsutherland** [comment]
Went ahead and rebased anyway, still trivial. :)

**Comment by jschueller** [comment]
ok

**Comment by jakirkham** [comment]
Alright, thanks all.

**Pull request merged**
