### PR TITLE
Added the list of ways to contact the conda-forge team readme.md

### PR DESCRIPTION
**Pull request by prachi237**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by prachi237** [comment]
By adding these  list of ways to contact the team  in the readme.md will be efficient. Though in docs it is mentioned in details about them, but I thought adding them in brief in readme.md fie will help the contributor.  
@viniciusdc  @beckermr  sir  please review😄

**Review by isuruf — CHANGES_REQUESTED** [review]
This should just be a link to https://conda-forge.org/docs/orga/getting-in-touch.html

**Comment by prachi237** [comment]
> This should just be a link to https://conda-forge.org/docs/orga/getting-in-touch.html

Yes sir that was mentioned as well, but I thought in addition  if we can add the list of getting in touch with the team in brief. It will save time of the contributor as they can directly get the access of all the links of channels and issues from readme.md file itself.

**Comment by prachi237** [comment]
@beckermr  sir I need ur suggestion on it, is it a good idea to add the list of contact  the org.  in readme.md in brief

**Comment by beckermr** [comment]
Follow what @isuruf said.

**Pull request closed without merging**
