### PR TITLE
Documented about Mamba 

### PR DESCRIPTION
**Pull request by PrernaSingh587**
This is a draft PR. I have documented about what mamba build is and how it may prove to be useful.

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs`
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by PrernaSingh587** [comment]
@viniciusdc Could you please check ? I have briefed about mamba here and added the links for the installation to the original mamba docs.  I have added the link on how to use mamba-build to maintainers_faq page. (This will be valid when the mamba-build part gets merged)

**Comment by leofang** [comment]
cc: @wolfv

**Comment by leofang** [comment]
Looks like this complements to #1353?

**Comment by ForgottenProgramme** [comment]
> Looks like this complements to #1353?


@PrernaSingh587 , nice work there. :)

But, look here Prerna: https://github.com/conda-forge/conda-forge.github.io/issues/1290#issuecomment-814380140
As commented, I was already working on documenting about mamba. 

It would be better if you could inform other community members (through Github comments) before you start working on any issue or a part of it. 
This way we could avoid two persons working on the same issue. Also, communication could lead to collaboration. 
Let's work together, next time? :) <3

**Comment by PrernaSingh587** [comment]
> > Looks like this complements to #1353?
> 
> 
> @PrernaSingh587 , nice work there. :)
> 
> But, look here Prerna: https://github.com/conda-forge/conda-forge.github.io/issues/1290#issuecomment-814380140
> As commented, I was already working on documenting about mamba. 
> 
> It would be better if you could inform other community members (through Github comments) before you start working on any issue or a part of it. 
> This way we could avoid two persons working on the same issue. Also, communication could lead to collaboration. 
> Let's work together, next time? :) <3

Yup . @viniciusdc and I had a discussion about this yesterday itself.

**Comment by ForgottenProgramme** [comment]
@PrernaSingh587 
No problem. 
Just put it on Github (comments or an issue) next time, so that others can know too. :)

**Review by beckermr — CHANGES_REQUESTED** [review]
This text is in the wrong spot. The knowledge base is for recipes

**Comment by viniciusdc** [comment]
> This text is in the wrong spot. The knowledge base is for recipes  

Sorry that was my bad, we were discussing  about build with mamba configuration to debug and forgot about that. Maybe this place sounds better https://conda-forge.org/docs/maintainer/adding_pkgs.html#miscellaneous ?

**Comment by beckermr** [comment]
if you want to document build_with_mambabuild, then look at the conda-forge.yml configuration section.

**Comment by PrernaSingh587** [comment]
New PR created #1381

**Pull request closed without merging**
