### PR TITLE
Corrected typos and grammar accross documentation

### PR DESCRIPTION
**Pull request by echoix**
This is one of my first contributions to a project, I hope I didn't do anything wrong :)

There is one last sentence that causes problems, it is on line 77 of src/orga/governance.rst, and should be reworded:

> Standard items are ones where **_public record and discourse and record_** is preferable. Sensitive voting items are ones where the results of the preferable.

Sorry for having a commit for each file, I was using the web editor, and can't squash the commits...

### CODE REVIEW

**Comment by dougalsutherland** [comment]
LGTM too.

I don't know whether we technically need a vote to merge bc it's editing the governance docs, but it's just typo fixes, so I'll let someone else decide whether to just hit the button. :)

**Comment by echoix** [comment]
And what about the sentence on line 77 of governance.rst, does anyone know what it means?

**Comment by jakirkham** [comment]
Are you referring to the types of things that are voted on?

**Comment by echoix** [comment]
Ok, yes I’ll do that! I didn’t understand the meaning of the sentence, so I couldn’t decide on my own ;)

**Comment by jakirkham** [comment]
No worries. Thanks for the fix 🙂

**Pull request merged**
