### PR TITLE
DOC added docs on automerge

### PR DESCRIPTION
**Pull request by beckermr**
I have added documentation on the automerge functionality. 

cc @jakirkham @conda-forge/bot

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @beckermr! Couple of questions:

1. Does the bot merge only passing PRs or could it merge a failing PR (if so what failures are allowed)?
2. Is human review still needed or will the bot merge without that?
3. If human review is still needed, how does one signal to the bot something is safe to merge?

**Comment by beckermr** [comment]
Right. These details are subject to change and so I didn't want to put too much information in the docs right now. I am happy to add a bit more though. 

The bot automerges only when all of the following conditions have been met:

1. the PR must have at least one passing status besides the linter (which is not fully reliable due to various bugs that need fixing :/)
2. the PR must be from the `regro-cf-autotick-bot` user
3. the feedstock must have `bot: automerge: True` set in the `conda-forge.yml` If no key is set at all, it currently defaults to `False` but this may change.
4. the PR must have `[bot-automerge]` set in the title
5. the `condaforge/rego-cf-autotick-bot-action:prod` docker image must exist

The bot does not require human review to merge.

So point 4 above is a way for people to turn off automerge on a specific PR from the bot. They can simply edit the title. 5 above is a mechanism for the bot maintainers to turn off automerge globally should something go horribly wrong. 3 above allows a feedstock to opt-out of automerge entirely.

**Comment by beckermr** [comment]
I've put more extensive docs here: https://github.com/regro/cf-scripts/pull/767

**Comment by jakirkham** [comment]
Thanks for those details. Should we add a link out to those docs?

**Comment by beckermr** [comment]
Yes!

**Comment by beckermr** [comment]
OK @jakirkham this one is ready to merge!

**Comment by beckermr** [comment]
bump @conda-forge/core too

**Comment by jakirkham** [comment]
Thanks @beckermr! Sorry I don't think I was awake yet 😉

**Pull request merged**
