### PR TITLE
add announcement for mambabuild

### PR DESCRIPTION
**Pull request by wolfv**
PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @ocefpaf

**Comment by wolfv** [comment]
I think for this we already had a tweet :) But for tensorflow-gpu it would also be cool (and mention that we have pytorch-gpu, too): https://github.com/conda-forge/blog/pull/48

**Comment by jakirkham** [comment]
Ok know Filipe had mentioned tweeting so wanted him to be aware.

That's great! Thanks Wolf 😄 Will read over that in a bit 🙂

**Comment by ocefpaf** [comment]
I want to tweet the announcement. We need to show folks that this media exists :smile:

**Pull request merged**
