### PR TITLE
Update boost pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
is the pinning bot still down ?

**Comment by jakirkham** [comment]
Yes. 😞 Tried to fix it a while back with PR ( https://github.com/conda-forge/conda-forge.github.io/pull/310 ), but have lacked the time to complete it. If you are interested, would happily look at a new PR to fix the bot.

**Comment by jschueller** [comment]
@jakirkham how can I test that script locally to debug ? it seems tied to the admin account. Can you show me a feedstock that it cannot update ?

**Comment by jakirkham** [comment]
Yeah I don't think you can test it locally that easily, which is definitely a problem. Though it looks like you figured it out.

**Comment by jschueller** [comment]
yes I isolated the few relevant bits

**Comment by jakirkham** [comment]
Went back and realized that `boost` actually broke ABI in the patch release. We need to update this to 1.65.1. All the SONAMEs changed and `libboost_regex` got some new symbols and removed some symbols as well.

ref: https://abi-laboratory.pro/tracker/objects_report/boost/1_65_0/1_65_1/report.html

**Comment by jschueller** [comment]
https://github.com/conda-forge/conda-forge.github.io/pull/455

**Pull request merged**
