### PR TITLE
Add proper note formatting

### PR DESCRIPTION
**Pull request by BastianZim**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

### CODE REVIEW

**Comment by BastianZim** [comment]
@viniciusdc I just checked that everything is correctly formatted and saw that a note wasn't correctly formatted as a note which is now bugging me. 😄

**Review by ForgottenProgramme — APPROVED** [review]

**Comment by BastianZim** [comment]
Will also fix the links at https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-anaconda-delay

**Comment by BastianZim** [comment]
Done @viniciusdc

**Review by viniciusdc — APPROVED** [review]
Great! LGTM

**Pull request merged**
