### PR TITLE
Correct the wrong dates.

### PR DESCRIPTION
**Pull request by pelson**
What a mess. Sorry for all the confusion.

@msarahan / @jakirkham / @patricksnape 
Was there anybody else who was planning to join us for the VS meeting (advertised as today, but actually tomorrow)?

I have added this as a section to our hackpad, which also includes a hangout link and the correct date & time.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @183amir, note the date of VC meeting has been corrected from today (Thursday) to Friday.

**Comment by 183amir** [comment]
@jakirkham thank you for telling me too but I am not sure I can make it. I will try though.

**Comment by jakirkham** [comment]
Sorry for the confusion. I do hope you can make it.

Either way, the notes should be in the hackpad ( http://conda-forge.hackpad.com/ ) so you can at least follow what is discussed. They will also be PR'd back into this repo for posterity.

**Comment by pelson** [comment]
Sorry @183amir - this is entirely my fault. The words we spoke, and the dates I wrote down were different, and one had to give. Even if you can't make this one, I hope you will be able join us some other time.

**Pull request merged**
