### PR TITLE
Add kkraus to core

### PR DESCRIPTION
**Pull request by kkraus14**

### CODE REVIEW

**Comment by beckermr** [comment]
Merge away @kkraus14!

**Comment by kkraus14** [comment]
> Merge away @kkraus14!

Any preferences regarding squash merging vs merge commits? 😄

**Comment by beckermr** [comment]
@isuruf?  ;p

**Comment by beckermr** [comment]
TL;DR use a merge commit if @isuruf is on the repo

**Comment by isuruf** [comment]
No squash commits

**Comment by isuruf** [comment]
If the person doing the merge is the sole author of the PR, it's fine to squash. Merge commit in every other case.

**Pull request merged**
