### PR TITLE
Modified Announcement Section

### PR DESCRIPTION
**Pull request by PrernaSingh587**
I have tried to modify the Announcement section to make it look a bit appealing. I have made sure there was no tampering with the content and the dates. I have checked if there was any mistake twice. All edits were in src files. Html files were not touched.

Screenshot from 2021-04-03 10-11-27

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs`
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by PrernaSingh587** [comment]
@viniciusdc  Hi, could you please tell me where I need to improve?

**Review by beckermr — CHANGES_REQUESTED** [review]
We cannot merge this as it will likely break the RSS feed of our announcements.

**Comment by PrernaSingh587** [comment]
@beckermr Hi, thanks for the review. So is there no way to modify the announcement section?

**Comment by beckermr** [comment]
You'll need to check that the RSS feed still works. If it doesn't, you'll have to modify the newsfeed package we have to work with the new format.

**Comment by PrernaSingh587** [comment]
> You'll need to check that the RSS feed still works. If it doesn't, you'll have to modify the newsfeed package we have to work with the new format.

Could you tell me which newsfeed package is used to create rss feeds?

**Comment by PrernaSingh587** [comment]
> You'll need to check that the RSS feed still works. If it doesn't, you'll have to modify the newsfeed package we have to work with the new format.

I have come to an understanding that sphinx-contrib is being used to generate rss content. Please help me to understand how to change the formatting so that this produces correct URL.

**Comment by beckermr** [comment]
I won't have time to help with this for several days. You may want to work on something else.

**Comment by viniciusdc** [comment]
> > You'll need to check that the RSS feed still works. If it doesn't, you'll have to modify the newsfeed package we have to work with the new format.
> 
> I have come to an understanding that sphinxcontrib-newsfeed is being used to generate rss content. Please help me to understand how to change the formatting so that this produces correct rss.

HI @PrernaSingh587 thanks for the PR, I had a feeling that it would break things but requested your PR for two reasons: 

- To check if those changes would really impact the current newsfeed process (What Matt clarified with his comment);

- To generate another contribution for Outreachy, even though this won't be merged it generates a path for your final proposal.

I will have a look at the newsfeed package and see if I can help you with that, in the meantime feel free to look further into our issue list and talk with me for any other possible directions.

**Pull request closed without merging**
