### PR TITLE
Update link to list of pinned versions

### PR DESCRIPTION
**Pull request by willirath**
The old wiki-page seems to be gone.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for the PR, @willirath.

So this should be moved to `src/conda-forge_gotchas.rst` as this is an autogenerated file that will be rewritten during doc generation.

That said, we are about to get rid of explicitly listing pinnings as it will be done for you as part of re-rendering (Wouldn't have expected you to know this). So maybe we should hold tight on this change.

Thoughts @conda-forge/core?

**Comment by scopatz** [comment]
I think this is fine for now.  I will merge in 24 hrs if no objections.

**Comment by jakirkham** [comment]
This should hopefully be clear after tomorrow's meeting.

**Comment by jakirkham** [comment]
> So this should be moved to `src/conda-forge_gotchas.rst` as this is an autogenerated file that will be rewritten during doc generation.

Could you please fix this point, @willirath?

**Comment by jakirkham** [comment]
Thanks. That would be good. :)

**Comment by willirath** [comment]
Done.

**Comment by pelson** [comment]
Thanks @willirath.

**Pull request merged**
