### PR TITLE
Update CFEP definition in the Glossary

### PR DESCRIPTION
**Pull request by viniciusdc**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

### CODE REVIEW

**Comment by beckermr** [comment]
Thank you!

**Review by beckermr — APPROVED** [review]

**Comment by prachi237** [comment]
https://conda-forge.org/docs/orga/cfep-index.html#index-of-cfeps even this has to be updated

**Comment by viniciusdc** [comment]
> https://conda-forge.org/docs/orga/cfep-index.html#index-of-cfeps even this has to be updated

@prachi237 you are right, that 'all' there is too powerful, could you follow Matt comment there and make a PR for it?

**Comment by prachi237** [comment]
> > https://conda-forge.org/docs/orga/cfep-index.html#index-of-cfeps even this has to be updated
> 
> @prachi237 you are right, that 'all' there is too powerful, could you follow Matt comment there and make a PR for it?

yes I will do that

**Comment by viniciusdc** [comment]
> > > https://conda-forge.org/docs/orga/cfep-index.html#index-of-cfeps even this has to be updated
> > 
> > 
> > @prachi237 you are right, that 'all' there is too powerful, could you follow Matt comment there and make a PR for it?
> 
> yes I will do that

Here https://github.com/conda-forge/cfep in the second paragraph of the readme too

**Pull request merged**
