### PR TITLE
DOC announce osx vm change

### PR DESCRIPTION
**Pull request by beckermr**
PR Checklist:

- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by beckermr** [comment]
cc @jaimergp @jakirkham

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

**Comment by mattip** [comment]
I see where github actions [has announced](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22) the end of the support for macOS 10.15, but I do not see a similar announcment on the [azure images](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) page nor on the [macOS azure runners](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) page. Did I miss another venue for announcements?

**Comment by mattip** [comment]
Ahh, it is a warning on the azure pipeline runs like [this one](https://dev.azure.com/numpy/numpy/_build/results?buildId=25324&view=results), sorry for the noise.

**Comment by jaimergp** [comment]
For reference: https://github.com/conda-forge/conda-forge.github.io/issues/1798

**Pull request merged**
