### PR TITLE
Remove avoiding-the-openblas-mkl-dance

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/conda-forge/conda-forge.github.io/issues/771

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Fine with me. I don't think we have a linked that section anywhere do we? If so we may want to change those links before we delete this.

I could not find it but I have to confess I only tried a few `find` keywords combinations at the CLI.  BTW, would sphinx `linkcheck` catch something like this? I know it catches external links, not sure about internal references.

**Comment by croth1** [comment]
Just thought about it again: since we never labelled the header, there should be no references. I think sphinx would warn automatically when you build locally. I think you can merge 👍

**Comment by ocefpaf** [comment]
> I think you can merge +1

You do have merge rights here, right? Just checking in case you need it...

**Comment by croth1** [comment]
@ocefpaf, yes I am maintainer here 👍

**Pull request merged**
