### PR TITLE
change master to main in commands

### LINKED ISSUE #1676: Change ``master`` to ``main`` in all the git commands.
### Where should the content be added?

At all the places where git commands are present.

### What should be added?

We should change all the git commands we have in our docs.

### Additional information

No response

### PR DESCRIPTION
**Pull request by ssurbhi560**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below
fixes #1676

### CODE REVIEW

**Review by kathatherine — APPROVED** [review]
LGTM!

**Comment by jakirkham** [comment]
Thanks @ssurbhi560! 🙏

Could you please resolve conflicts? Then think we can merge

**Comment by ssurbhi560** [comment]
Hi @jakirkham, thanks for reminding! :) 
I have resolved all the conflicts.

**Comment by jakirkham** [comment]
Thank Surbhi! 🙏

**Pull request merged**
