### PR TITLE
Add automated dependency license file generating

### PR DESCRIPTION
**Pull request by BastianZim**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

Brought up in 

* https://github.com/sstadick/cargo-bundle-licenses
* https://github.com/conda-forge/conda-forge.github.io/issues/1052
* https://github.com/conda-forge/staged-recipes/pull/18107

### CODE REVIEW

**Comment by BastianZim** [comment]
CC @sstadick @m-rossi

**Comment by sstadick** [comment]
@BastianZim This seems great to me! My only concern is the still-open MacOS ARM issue in the feedstock for `cargo-bundle-licenses`.

Thank you for writing this up.

**Comment by BastianZim** [comment]
> @BastianZim This seems great to me! My only concern is the still-open MacOS ARM issue in the feedstock for `cargo-bundle-licenses`.

Yes, that probably needs to be solved simultaneously. Also linking the PR in case someone has an idea https://github.com/conda-forge/cargo-bundle-licenses-feedstock/pull/6

**Comment by BastianZim** [comment]
@conda-forge/core All related issues have been solved, ready for review!

**Review by pkgw — APPROVED** [review]
LGTM! This was helpful in adding license packaging to Tectonic.

**Comment by BastianZim** [comment]
@conda-forge/core Gentle ping here.

**Comment by BastianZim** [comment]
@conda-forge/core Gentle ping here.

**Comment by hmaarrfk** [comment]
Thanks for the good docs!

**Pull request merged**
