### PR TITLE
Add enum34 to empty packages

### PR DESCRIPTION
**Pull request by BastianZim**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

Ref:

* https://github.com/conda-forge/enum34-feedstock/blob/e888df2bb048142fae8e31a140116622539efb4e/recipe/meta.yaml#L14
* https://github.com/conda-forge/enum34-feedstock/commit/7511d25dd9b9852259c71c057ea661966d1e8d62 For Python2.7

### CODE REVIEW

**Comment by BastianZim** [comment]
Well that's not really empty, it can just be installed under all versions, right? Let me create a second table and add it there.

Side note: I think it would be good to have a json somewhere with this so that Grayskull etc. can read this automatically and we can maybe add this to the linter. Where would be a good place?

**Comment by beckermr** [comment]
Cc @mariusvniekerk 

We need a data service.

**Comment by beckermr** [comment]
We can store a table in the bot metadata if you'd like. This is where depfinder and gray skull get lots of other info.

**Comment by BastianZim** [comment]
@marcelotrevisani Any preference? 

Xref https://github.com/conda-incubator/grayskull/issues/216

**Comment by beckermr** [comment]
> Are there any other packages besides importlib metadata that should be added?

We could go through any of the various things that have been migrated to the stdlib over the years, but I think starting a list is good enough for here. LGTM!

**Review by beckermr — APPROVED** [review]

**Comment by BastianZim** [comment]
Great! Then feel free to merge it, or should we wait for more input?

I'd suggest continuing the discussion about the list in https://github.com/conda-incubator/grayskull/issues/216 just to have it focused.

**Pull request merged**
