### PR TITLE
update macos docs

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge/core, this is ready for review

**Review by ocefpaf — APPROVED** [review]

**Comment by ocefpaf** [comment]
LGTM but and I can understand the problem and the explanation. Let's just wait for another person to read this b/c clarity there is important.

**Comment by wolfv** [comment]
Maybe adding the libcxx compatibility trick would be nice, too

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
> Maybe adding the libcxx compatibility trick would be nice, too

Would be nice but that can be done in a follow-up PR.

**Comment by xhochy** [comment]
Thanks @isuruf !

**Pull request merged**
