### PR TITLE
Add note about how to handle broken packages

### PR DESCRIPTION
**Pull request by ericdill**
Addresses #181

### CODE REVIEW

**Comment by ericdill** [comment]
@ocefpaf @jakirkham  -- first pass at throwing this into the docs. Do you think this is going in the right direction or should this go through a CFEP?

**Comment by ocefpaf** [comment]
> first pass at throwing this into the docs. Do you think this is going in the right direction

Yep. Looks good to me.

> or should this go through a CFEP?

Please no :smile:

**Comment by ericdill** [comment]
Thanks @ocefpaf :)

**Comment by ericdill** [comment]
Double thanks for avoiding a CFEP ):

**Comment by jakirkham** [comment]
Thanks all. :)

**Pull request merged**
