### PR TITLE
Add Gitter link on the website

### LINKED ISSUE #73: Add gitter badge/info to website
Would be nice if we could make our use of gitter (namely where we are) more visible so people can find help quickly.

### PR DESCRIPTION
**Pull request by ssurbhi560**
PR Checklist:

- [ ] ~~make all edits to the docs in the `src` directory, not in `docs` or in the html files~~
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below
    fixes #73

### CODE REVIEW

**Comment by ssurbhi560** [comment]
Please review @jakirkham @kathatherine!

**Review by jakirkham — APPROVED** [review]

**Comment by ssurbhi560** [comment]
@jakirkham why are these checks failing? It shows that there are some broken links, but I didn’t make any changes within those files. Please let me know how I go about fixing this.

**Comment by jakirkham** [comment]
Not sure. Trying a trivial PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1710 ) to see what's up

**Comment by jakirkham** [comment]
Think we fixed the issue with PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1714 ). Restarting CI...

**Review by kathatherine — APPROVED** [review]
Looks good to me as long as we can get those checks to pass!

**Comment by jakirkham** [comment]
Thought that would grab the latest changes from `main` 😞

Closing/reopening...

(if this doesn't work, @ssurbhi560, would merge the latest `main` into your branch or rebase)

**Comment by ssurbhi560** [comment]
Thanks a lot for the help @jakirkham! :)

**Comment by jakirkham** [comment]
Woot! Glad that worked 😄

Thanks for working with us here, Surbhi! 🙏

**Pull request merged**
