### PR TITLE
 Fix #1729; Add virtual environment (VENV) to glossary section 

### LINKED ISSUE #1729: Add virtual environment (VENV) to glossary section
### Where should the content be added?

Glossary under Miscellaneous section

### What should be added?

Meaning of virtual environment  

### Additional information

Considering the recommendation that packages be installed with conda-forge in a new environment aside from the base environment, it would be very helpful especially for a new user, to understand what a virtual environment is, making the essence of the recommendation much clearer.

### PR DESCRIPTION
**Pull request by Hil-dred**
Hello @beckermr @kathatherine, I have created this PR as a solution to issue #1729

### CODE REVIEW

**Review by kathatherine — APPROVED** [review]
Looks great to me!

**Comment by jakirkham** [comment]
Are we using the `venv` term somewhere? Did a quick search, but didn't find anything

**Comment by Hil-dred** [comment]
Hello @jakirkham, in the 'How can I install packages with condaforge' section of the User documentation, there is a note that recommends users creating environments for installing packages rather than using the base environment. The term 'environment' will make sense to an experienced user but a first time user may need some explanation on what that means to get the essence of this recommendation.

**Comment by jakirkham** [comment]
That make sense. Though in that case would drop `VENV` here and just say `Environment`

**Comment by Hil-dred** [comment]
@jakirkham works fine. I'll make the change and pull a new request

**Comment by jaimergp** [comment]
Superseded by https://github.com/conda-forge/conda-forge.github.io/pull/1759

**Pull request closed without merging**
