### PR TITLE
Improved Readme.md file

### PR DESCRIPTION
**Pull request by prachi237**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by beckermr** [comment]
This change doesn't look very nice. I am not in favor of merging.

**Comment by prachi237** [comment]
> This change doesn't look very nice. I am not in favor of merging.

umm if I could have got the logo in color white it would have looked better. No issues I am closing the PR😄😅

**Comment by prachi237** [comment]
Screenshot (1)
@beckermr  sir, the logo previously I added was not visible clearly. I changed that now, but I needed a suggestion , will it be ok to add logo in the readme.md file🤔

**Comment by beckermr** [comment]
I don't think that screenshot looks better than what we have.

**Pull request closed without merging**
