### PR TITLE
Improved Readme docs #1300

### PR DESCRIPTION
**Pull request by prachi237**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs`
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by prachi237** [comment]
Screenshot (79)

**Comment by prachi237** [comment]
Screenshot (78)

**Comment by PrernaSingh587** [comment]
@viniciusdc  Do we need to update the part where it says to install Sphinx ? Because I guess we figured yesterday that it does not really install the newsfeed and we have to use the pip command to have that finally installed.

**Comment by prachi237** [comment]
> @viniciusdc Do we need to update the part where it says to install Sphinx ? Because I guess we figured yesterday that it does not really install the newsfeed and we have to use the pip command to have that finally installed.

Actually I just tested it in my local directory, I had not made any changes in docs file. once this gets merged it will automatically generate the html file.

**Review by beckermr — CHANGES_REQUESTED** [review]
The correct list of steps is in the readme for the repo. This list should match that.

**Comment by prachi237** [comment]
> The correct list of steps is in the readme for the repo. This list should match that.

ok sir I didn't know that earlier, I opened the issue to reformat the text arrangement to make it more user friendly, well I will update the content as well

**Comment by beckermr** [comment]
Awesome. All fixes are greatly appreciated!

**Comment by viniciusdc** [comment]
> > The correct list of steps is in the readme for the repo. This list should match that.
> 
> ok sir I didn't know that earlier, I opened the issue to reformat the text arrangement to make it more user friendly, well I will update the content as well

Hi @prachi237 how is it going? the contents Matt comment are [here](https://github.com/conda-forge/conda-forge.github.io/blob/master/README.md),once you finish this changes ping me here and I will review it :smile:

**Comment by prachi237** [comment]
> > > The correct list of steps is in the readme for the repo. This list should match that.
> > 
> > 
> > ok sir I didn't know that earlier, I opened the issue to reformat the text arrangement to make it more user friendly, well I will update the content as well
> 
> Hi @prachi237 how is it going? the contents Matt comment are [here](https://github.com/conda-forge/conda-forge.github.io/blob/master/README.md#building-the-docs),once you finish this changes ping me here and I will review it 😄

sir please once review the issue #1305 I made the required changes, once that gets updated then I can go with this issue , issue #1305 deals with the change in readme.md file .

**Comment by beckermr** [comment]
Feel free to make the required changes here in this PR. :)

**Comment by viniciusdc** [comment]
@prachi237 woudl you want to add more information into this PR?

**Comment by prachi237** [comment]
> @prachi237 woudl you want to add more information into this PR?

Yes sir, some more info in to be added.

**Comment by prachi237** [comment]
I'll try to add them by tonight and send the pr

**Pull request closed without merging**
