### PR TITLE
RFC: Add script to mirror packages from one conda channel to another conda channel

### PR DESCRIPTION
**Pull request by ericdill**
This came up in discussion on conda-forge/staged-recipes#593.  @ocefpaf
suggested that scripts/ in this repo might be a good home for this script.

Thoughts?

### CODE REVIEW

**Comment by msarahan** [comment]
cc @mcg1969

**Comment by mcg1969** [comment]
I have such a script... I'll share

**Comment by jakirkham** [comment]
Sounds like a good home. Let's try and combine forces on the script so we can have something that works for everyone.

**Comment by pelson** [comment]
In all honesty, I don't think this belongs in conda-forge/conda-forge.github.io. We already have scripts in here which are starting to prove useful outside of conda-forge's domain, and this will clearly be another one. This is ripe for its own package (small, self contained, clear scope) and I suspect it will get more visibility as such.

Thoughts @ericdill?

**Comment by ericdill** [comment]
> In all honesty, I don't think this belongs in conda-forge/conda-forge.github.io

That seems reasonable. I'm starting to use this internally to mirror anaconda.org/conda-forge to the anaconda server at nsls2 and have made some improvements to handle this use case.

Are you thinking that I should just publish this as its own repo on github? something like `conda-mirror`?

**Comment by ChrisBarker-NOAA** [comment]
On Thu, Jun 30, 2016 at 9:43 AM, Eric Dill <notifications@github.com> wrote:

> Are you thinking that I should just publish this as its own repo on
> github? something like conda-mirror?
>
>
it seems that the conda-forge organization is a reasonable home for it --
but it it's own repo.

-CHB

-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by pelson** [comment]
I'm going to close this one. This is a pretty useful tool, and it might even be a healthy thing for [anaconda-client](https://github.com/Anaconda-Platform/anaconda-client) to support.

**Comment by ericdill** [comment]
It is on my todo list to actually package this script as its own project.

**Pull request closed without merging**
