### PR TITLE
Adding Guidelines

### PR DESCRIPTION
**Pull request by Radhika-Saini**
1. 

PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

### CODE REVIEW

**Comment by Radhika-Saini** [comment]
I need help. actually, My Last changes to the last PR are also shown here.
How can I remove them to only show the latest changes?

**Comment by ssurbhi560** [comment]
Hi @Radhika-Saini, I would suggest you close this PR and create a new branch for making changes for this issue (it is good practice to create a new branch for every new PR/change).
After that, make changes required for this particular issue, and after committing and pushing those changes, open a PR again. You can refer to [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) or [this](https://alvinalexander.com/git/how-to-create-pull-request-on-github-notes-steps/) for help.

Using git can be a little overwhelming initially; we all end up messing up with it at one point or another. I would suggest you keep [this](https://alvinalexander.com/git/how-to-create-pull-request-on-github-notes-steps/) handy. Let us know if you need any more help. :)

**Comment by Radhika-Saini** [comment]
@ssurbhi560  Yes I need help.
Can we have a google meet?
Still facing the same issue.

**Comment by ssurbhi560** [comment]
What is the issue you are facing @Radhika-Saini? You can share screenshots or error messages here if you want.

**Pull request closed without merging**
