### PR TITLE
[Vote; needs 9 yeas] subteam for bot

### PR DESCRIPTION
**Pull request by CJ-Wright**
@conda-forge/core ready for review!

### CODE REVIEW

**Comment by ocefpaf** [comment]
@bgruening I recommend creating something similar for `R` if you think it may be useful.

**Comment by CJ-Wright** [comment]
We most likely need to do this for all the help teams (although I would be happy to have an acknowledgement of their existence on the staged recipes PR template :smiling_imp:)

I think the bigger one would be the bioconda group.

**Comment by bgruening** [comment]
> @bgruening I recommend creating something similar for R if you think it may be useful.

Yes, I do think this is useful! Thanks!

**Comment by CJ-Wright** [comment]
As a point of clarification, this PR needs 50% of yeas from core to pass. Would it be possible to leave Approve (yea) or Request Changes (nay) as a form of voting? (if you want specific changes before voting, please leave a comment and I'll try to get to it)

**Comment by ocefpaf** [comment]
> As a point of clarification, this PR needs 50% of yeas from core to pass. 

@CJ-Wright how do you want to do it? Number of :+1: on the first comment or "PR approvals"?

**Comment by CJ-Wright** [comment]
PR approvals if possible (this is the first one so I guess we need to experiment).

**Comment by scopatz** [comment]
Maybe you should request reviews for all of core, then, please.

**Comment by scopatz** [comment]
Also, this has not been added to any table of contents, so it won't be built with the website ;)

**Comment by ocefpaf** [comment]
> Maybe you should request reviews for all of core, then, please.

Done in https://github.com/conda-forge/conda-forge.github.io/pull/627#issue-207707729 :smile: 

We should just make clear that we **actually need** them to review this time :smile:

**Comment by CJ-Wright** [comment]
I did not know you could also "request review" from an entire team.

**Comment by scopatz** [comment]
@CJ-Wright - That doesn't really work :frowning_face:, because any member of core can review on behalf of the whole team

**Comment by CJ-Wright** [comment]
That's too bad, I was hoping that feature would get everyone.

**Comment by CJ-Wright** [comment]
@scopatz it seems that more than one person can review on the behalf of core, so maybe this is ok. I just need to discount any double votes.

**Comment by scopatz** [comment]
I think we just shouldn't use the this feature, because it doesn't do what we think it does

**Comment by CJ-Wright** [comment]
Fair, it would be nice if we could set the number of approvals for each PR, since that would make the vote threshold easier.

**Comment by CJ-Wright** [comment]
@conda-forge/core This vote now has 9 yea votes, constituting a (50% + 1) majority of the core team. I'm going to leave this PR open for another 24 hours to allow any dissenting core members to voice their concerns and barring any major issues merge.

**Comment by scopatz** [comment]
@CJ-Wright - note that the governance document says that:

> The default voting period is 1 week (7 days). This may be modified at the time when a vote is called, but may never be less than 24 hrs.

Merging tomorrow would only be 5 days.  I think this needs to remain open until Friday, at least.

**Comment by scopatz** [comment]
The reason being that people can change their vote etc and this is not unanimous since there remain many abstentions.

**Comment by CJ-Wright** [comment]
Ah ok. I guess we need to keep more formal meeting notes for this kind of thing so we can refer back.

**Comment by CJ-Wright** [comment]
The ayes have it.

**Pull request merged**
