### PR TITLE
Set mpi variable

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@minrk, can you please take a look?

**Comment by davidbrochart** [comment]
When mpi is defined in conda_build_config.yaml:
```
mpi:
  - mpich
  - openmpi
```
and not in meta.yaml, the linter fails. We need to add in meta.yaml e.g.:
```
{% set mpi = mpi or 'mpich' %}
```

**Comment by isuruf** [comment]
Can you send a PR to conda-smithy to fix this in the linter? (Add `mpi` to https://github.com/conda-forge/conda-smithy/blob/0a678de0319a78cf29b56b3a0e3f93c19692670b/conda_smithy/utils.py#L61)

**Comment by minrk** [comment]
Yeah, this has been required (seems to be on and off, not sure why). Great that there is a simple fix in conda-smithy!

I think there should in the long run be a general fix that conda-smithy is not rendering in a realistic context, and it should use conda_build_config.yaml to create a realistic default set of environment variables for any recipe, rather than forcing conda-smithy to know about every possible variable with a default value.

**Comment by leofang** [comment]
I suppose this can be closed?

**Pull request closed without merging**
