### PR TITLE
WIP python 2.7 deprecation

### PR DESCRIPTION
**Pull request by beckermr**

### CODE REVIEW

**Comment by scopatz** [comment]
Woah, weird.  What is the conda-forge-coordinator?

**Comment by beckermr** [comment]
We need to get our bots and keys under control. I am putting CFEP-14 up for a vote.

**Comment by jakirkham** [comment]
Based on offline conversation it seems like the bot is doing what is expected here (though we may want to change the code if we haven't already). Namely it just pushes commits from non-`master` branches on this repo to `master`.

**Comment by beckermr** [comment]
Wait is that supposed to be what it is doing?

**Comment by jakirkham** [comment]
That's what the code is doing. What it should do is certainly up for discussion 🙂

**Comment by isuruf** [comment]
> Namely it just pushes commits from non-master branches on this repo to master.

That's certainly not the intention of the code. Why do you say that?
It's just a typo. `((` instead of `[[`

**Pull request merged**
