### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by angeloobeta**
PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs`
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below
- [ ] Added favicon that serves as branding for the documentation website. Its main purpose is to help visitors locate the documentation page easier when they have multiple tabs open. Due to their tiny size, favicon work best as simple images or one-to-three characters of text
- [ ] Creating a favicon is a small but important step to setting up a Conda-forge  documentation website. It would legitimacy to the Conda-forge site and helps boost the online documentation. They are an immediate visual marker for the website which enables easy and quick identification for web users as well as unifies all of the various browser components into a well branded browsing experience.

### CODE REVIEW

**Comment by angeloobeta** [comment]
I added the conda-forge favicon that serves as branding for the documentation website. Its main purpose is to help visitors locate the documentation page easier when they have multiple tabs open. Due to their tiny size, favicon work best as simple images or one-to-three characters of text.

**Review by beckermr — CHANGES_REQUESTED** [review]
Please read the PR template. You cannot edit the files in the docs directory.

**Comment by viniciusdc** [comment]
@angeloobeta thanks for your PR, but as Matt mentioned this HTML files are auto generated, so if you want to modify it, you need to do it inside the `.src` folder.

**Comment by viniciusdc** [comment]
For the favicon option, I think you can have a look into the cloud-sphinx theme (we use that) and if I remember there is an extra option for this

**Comment by BastianZim** [comment]
See https://github.com/conda-forge/conda-forge.github.io/blob/d3354c6d7961c4baed103e90c5684a9b2f5debc0/src/conf.py#L159 (If I'm not mistaken)

**Comment by BastianZim** [comment]
@viniciusdc @beckermr Do we have an image/file that could be used as a favicon?

**Pull request closed without merging**
