### PR TITLE
Enable pre-commit for autoformatting files

### PR DESCRIPTION
**Pull request by goanpeca**
This is still not running the pre-commit checks while other PRs are merged. The step in deploy will fail until those files are included in the PR or ignored by the hook in case we do not want to modify them (e.g. minutes?)

[Pre-commit results](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:18)

Closes #1691

### CODE REVIEW

**Comment by goanpeca** [comment]
@jaimergp do we wanto to run the pre-commit on this PR or do we wait for https://github.com/conda-forge/conda-forge.github.io/pull/2084 ?

**Comment by jaimergp** [comment]
Let's wait for #2084 and maybe ignore the minutes for now.

**Comment by goanpeca** [comment]
This is the current list of fixes @jaimergp 

```
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing SECURITY.md
Fixing scripts/display_linkcheck.py
Fixing misc/circle_ci_pkgs_dec2022_breach.json
Fixing static/img/attribution.txt
Fixing scripts/watch_only_my_feedstocks.py
Fixing scripts/list_deps.py
Fixing news/2023-01-08-conda-forge-staged-recipes-feedstock-creation-job-moved.md
Fixing .prettierignore
Fixing LICENSE
Fixing scripts/regenerate_feedstock.py

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing .github/ISSUE_TEMPLATE/docs_error_template.yml
Fixing .ci_scripts/render_templated_content.py
Fixing news/2020-03-18-python-27-and-vs2008-deprecation.md
Fixing scripts/display_linkcheck.py
Fixing src/pages/packages.jsx
Fixing scripts/watch_only_my_feedstocks.py
Fixing news/2022-02-13-default-branch-migration-from-master-to-main.md
Fixing .github/ISSUE_TEMPLATE/docs_suggestion_template.yml
Fixing news/2020-05-28-new-process-for-marking-packages-as-broken.md
Fixing news/2020-07-16-core-dependency-tree-package-changes.md
Fixing vote-results/2020_03_[19](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:20)_cfep-15.md
Fixing README.md
Fixing src/pages/announcements.md

check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for broken symlinks............................(no files to check)Skipped
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

docs/user/faq.md
vote-results/[20](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:21)20_03_29_cfep-14.md
news/20[21](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:22)-09-30-defaults-channel-is-now-dropped-when-building-conda-forge-packages.md
docs/user/talks.md
news/2020-10-08-compiler-upgrade-to-gcc-930.md
README.md
docs/orga/funding/gsod-2023.md
misc/DEV_MEETING_TEMPLATE.md
docs/maintainer/pinning_deps.md
news/2020-03-24-vs2015-to-vs2017-transition.md
vote-results/2020_02_vote_timeouts.md
docs/user/how_to_get_help.md
docs/orga/subteams.md
docs/maintainer/conda_forge_yml.md
news/2021-10-13-gcc-10-and-clang-12-as-default-compilers-for-linux-and-macos.md
vote-results/TEMPLATE.md
docs/index.md
static/js/count.js
docs/user/ci-skeleton.md
vote-results/2020_03_12_cfep-13.md
news/2019-03-28-we-overhauled-the-blas-support-in-conda-forge.md
docs/maintainer/updating_pkgs.md
docs/maintainer/infrastructure.md
SECURITY.md
docs/user/contributing.md
news/2020-07-16-core-dependency-tree-package-changes.md
news/20[22](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:23)-02-13-default-branch-migration-from-master-to-main.md
news/2021-11-17-clouddroneio-no-longer-working.md
docs/maintainer/adding_pkgs.md
docs/orga/guidelines.md
.github/ISSUE_TEMPLATE/docs_error_template.yml
news/2020-07-[23](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:24)-centos-7-sysroot-now-available-for-linux-64-builds.md
src/pages/announcements.md
news/2020-03-18-python-[27](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:28)-and-vs2008-deprecation.md
news/2019-09-[30](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:31)-clang-900-and-gfortran-[73](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8053121240/job/21994762645?pr=2085#step:4:74)0-as-default-compilers-in-osx.md
docs/maintainer/maintainer_faq.md
news/2020-07-15-cfep-18-removing-static-libraries-from-the-main-build.md
docusaurus.config.js
misc/circle_ci_pkgs_dec2022_breach.json
news/2019-01-22-it-has-happened-conda-forge-has-migrated-to-the-latest-compilers.md
news/2020-08-07-completed-new-staging-process-for-anacondaorg-uploads.md
docs/contracting/index.md
.github/ISSUE_TEMPLATE/general_template.yml
.github/ISSUE_TEMPLATE/error_template.yml
docs/misc/index.md
vote-results/2020_03_19_cfep-15.md
news/2022-11-16-moving-to-conda-artifacts.md
docs/orga/getting-in-touch.md
docs/maintainer/knowledge_base.md
docs/orga/funding/gsoc-2023.md
news/2020-07-03-cf-mark-broken-renamed-to-admin-requests.md
```
Which ones should we ignore, and which ones should we enforce?

**Comment by jaimergp** [comment]
> Which ones should we ignore, and which ones should we enforce?

I think we can safely ignore `scripts/`,  `static/`, `.github/`, `vote-results/`, `misc/`. Let's see how the list looks like after that.

**Comment by goanpeca** [comment]
Updated pre-commit results:

```bash
check yaml...............................................................Passed
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing news/2023-01-08-conda-forge-staged-recipes-feedstock-creation-job-moved.md
Fixing SECURITY.md
Fixing LICENSE
Fixing docs/sidebar.json

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing src/pages/packages.jsx
Fixing news/2020-05-28-new-process-for-marking-packages-as-broken.md
Fixing src/pages/announcements.md
Fixing news/2020-03-[18](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:19)-python-27-and-vs2008-deprecation.md
Fixing news/2022-02-13-default-branch-migration-from-master-to-main.md
Fixing news/2020-07-16-core-dependency-tree-package-changes.md
Fixing docs/maintainer/knowledge_base.md
Fixing vote-results/2020_03_[19](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:20)_cfep-15.md
Fixing README.md

check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for broken symlinks............................(no files to check)Skipped
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

news/[20](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:21)20-08-07-completed-new-staging-process-for-anacondaorg-uploads.md
docs/sidebar.json
news/2020-07-16-core-dependency-tree-package-changes.md
docusaurus.config.js
docs/maintainer/updating_pkgs.md
docs/orga/funding/gsoc-2023.md
docs/maintainer/maintainer_faq.md
docs/user/how_to_get_help.md
news/2019-01-22-it-has-happened-conda-forge-has-migrated-to-the-latest-compilers.md
news/20[21](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:22)-09-30-defaults-channel-is-now-dropped-when-building-conda-forge-packages.md
docusaurus.sidebars.js
news/20[22](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:23)-02-13-default-branch-migration-from-master-to-main.md
news/2020-03-24-vs2015-to-vs2017-transition.md
docs/orga/getting-in-touch.md
docs/contracting/index.md
news/2021-11-17-clouddroneio-no-longer-working.md
docs/orga/funding/gsod-20[23](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:24).md
SECURITY.md
news/2022-11-16-moving-to-conda-artifacts.md
docs/user/contributing.md
docs/maintainer/conda_forge_yml.md
.pre-commit-config.yaml
news/2020-03-18-python-[27](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:28)-and-vs2008-deprecation.md
docs/glossary.md
docs/maintainer/adding_pkgs.md
README.md
docs/user/ci-skeleton.md
docs/maintainer/knowledge_base.md
news/2021-10-13-gcc-10-and-clang-12-as-default-compilers-for-linux-and-macos.md
docs/user/faq.md
docs/orga/subteams.md
docs/user/talks.md
docs/maintainer/pinning_deps.md
news/2020-07-03-cf-mark-broken-renamed-to-admin-requests.md
docs/maintainer/infrastructure.md
news/2019-09-30-clang-900-and-gfortran-730-as-default-compilers-in-osx.md
src/pages/announcements.md
docs/orga/guidelines.md
docs/index.md
news/2020-10-08-compiler-upgrade-to-gcc-930.md
news/2019-03-[28](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:29)-we-overhauled-the-blas-support-in-conda-forge.md
news/2020-07-23-centos-7-sysroot-now-available-for-linux-[64](https://github.com/conda-forge/conda-forge.github.io/actions/runs/8090672565/job/22108518395?pr=2085#step:4:65)-builds.md
```

**Comment by jaimergp** [comment]
I saw that conda-smithy is using pre-commit.ci in the repo, so maybe we can also add it here. I also wonder if we should commit the current output of `pre-commit run --all-files` (see below), or just let each PR fix the affected files little by little.

```
check yaml...............................................................Passed
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing community/_sidebar.json
Fixing community/code-of-conduct.md
Fixing community/minutes.mdx
Fixing LICENSE
Fixing news/2023-01-08-conda-forge-staged-recipes-feedstock-creation-job-moved.md
Fixing SECURITY.md

trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing .ci_scripts/render_templated_content.py
Fixing .github/ISSUE_TEMPLATE/docs_error_template.yml
Fixing .github/ISSUE_TEMPLATE/docs_suggestion_template.yml
Fixing .github/workflows/deploy.yml
Fixing community/code-of-conduct.md
Fixing community/minutes.mdx
Fixing docs/maintainer/knowledge_base.md
Fixing news/2020-03-18-python-27-and-vs2008-deprecation.md
Fixing news/2020-05-28-new-process-for-marking-packages-as-broken.md
Fixing news/2020-07-16-core-dependency-tree-package-changes.md
Fixing news/2022-02-13-default-branch-migration-from-master-to-main.md
Fixing news/2024-03-06-dropping-cuda-112.md
Fixing src/pages/announcements.md
Fixing src/pages/packages.jsx

check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for broken symlinks............................(no files to check)Skipped
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook
blog/2020-03-05-grayskull.md
community/_sidebar.js
community/_sidebar.json
community/code-of-conduct.md
community/contracting.md
community/funding/gsoc-2023.md
community/funding/gsod-2023.md
community/getting-in-touch.md
community/subteams.md
docs/_sidebar.js
docs/_sidebar.json
docs/glossary.md
docs/index.md
docs/maintainer/adding_pkgs.md
docs/maintainer/conda_forge_yml.md
docs/maintainer/guidelines.md
docs/maintainer/infrastructure.md
docs/maintainer/knowledge_base.md
docs/maintainer/maintainer_faq.md
docs/maintainer/pinning_deps.md
docs/maintainer/updating_pkgs.md
docs/user/ci-skeleton.md
docs/user/contributing.md
docs/user/faq.md
docs/user/talks.md
docusaurus.config.js
news/2019-01-22-it-has-happened-conda-forge-has-migrated-to-the-latest-compilers.md
news/2019-03-28-we-overhauled-the-blas-support-in-conda-forge.md
news/2020-03-24-vs2015-to-vs2017-transition.md
news/2020-07-03-cf-mark-broken-renamed-to-admin-requests.md
news/2020-07-15-cfep-18-removing-static-libraries-from-the-main-build.md
news/2020-07-16-core-dependency-tree-package-changes.md
news/2020-07-23-centos-7-sysroot-now-available-for-linux-64-builds.md
news/2020-08-07-completed-new-staging-process-for-anacondaorg-uploads.md
news/2020-10-08-compiler-upgrade-to-gcc-930.md
news/2021-09-30-defaults-channel-is-now-dropped-when-building-conda-forge-packages.md
news/2021-10-13-gcc-10-and-clang-12-as-default-compilers-for-linux-and-macos.md
news/2021-11-17-clouddroneio-no-longer-working.md
news/2022-02-13-default-branch-migration-from-master-to-main.md
news/2022-11-16-moving-to-conda-artifacts.md
news/2024-03-06-dropping-cuda-112.md
README.md
SECURITY.md


ruff-format..............................................................Failed
- hook id: ruff-format
- files were modified by this hook

1 file reformatted, 1 file left unchanged
```

**Comment by jaimergp** [comment]
@conda-forge/core this is ready for review. We should probably configure the repo to use pre-commit.ci as conda-smithy is doing now. I think it's just a matter of enabling the app in this repo (it's already installed in the org).

**Review by xhochy — APPROVED** [review]

**Comment by jaimergp** [comment]
pre-commit.ci autofix

**Comment by jaimergp** [comment]
I enabled pre-commit.ci and it insisted on formatting everything, so I committed those changes and will add ignore-rev in a separate PR.

**Pull request merged**
