### PR TITLE
Embed timezone-aware calendar for community meetings

### PR DESCRIPTION
**Pull request by jaimergp**
PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] if you are adding a new page under `docs/` or `community/`, you have added it to the sidebar in the corresponding `_sidebar.json` file
- [ ] put any other relevant information below

Bringing the same calendar we have in conda.org now that it's prettier and can be made timezone-aware. xref https://github.com/conda/conda-dot-org/pull/221

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
We should put this on its own page outside of the meeting minutes with the page name calendar or similar. People won't find it buried at the top of the meeting minutes.

**Comment by beckermr** [comment]
Or we change the meeting minutes title to community meetings. Need a redirect in that case.

**Comment by jaimergp** [comment]
WDYT now? :) URLs didn't change despite the menu rearrangement.

**Review by beckermr — APPROVED** [review]
LGTM! Sometimes google fails to load the calendar for me, but maybe that is normal.

**Comment by jaimergp** [comment]
@kathatherine was reporting something similar in https://github.com/conda/conda-dot-org/pull/221 but I can't reproduce 🤔

**Comment by beckermr** [comment]
Yeah that's fine. It might be the preview app itself and it does work sometimes. Let's merge and see if maybe it works ok then.

**Pull request merged**
