### PR TITLE
[WIP] Clean up broken bits and links in the docs

### PR DESCRIPTION
**Pull request by croth1**
I will continuously fix small doc issues here, please feel free to comment, but do not merge just yet 😄 

- [x] remove references to CircleCI from the docs.

### CODE REVIEW

**Comment by jaimergp** [comment]
I have a used 404 checkers in CI in the past. Maybe it's a valuable addition here!

For example:

* https://github.com/marketplace/actions/404-links
* https://github.com/marketplace/actions/broken-link-check
* https://github.com/JustinBeckwith/linkinator-action

And I am sure there are others.

**Comment by croth1** [comment]
Yea, I am thinking about doing the checks automatically - will have a look into your suggestions, thanks. So far I used `linkcheck` directly from sphinx. It works, but I see two issues/downsides:

1. it also reports broken links in the meeting minutes, which I don't think are worth maintaining. I will need to find a way to prevent that.
2. there are a lot of github links and github's API seems to throttle the number of requests we can send. It might not be fast enough for checking for every commit.

**Comment by jaimergp** [comment]
I have asked my colleagues for their experience in this task, and @melissawm recommends the following:

> * Sphinx catches some dead links with -n (nitpicky mode) https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-n
> * I recently also learned about Lychee: https://github.com/lycheeverse/lychee
> * This has been configured in napari if you want to see how it looks like in action: https://github.com/napari/napari.github.io/blob/main/.github/workflows/link-checker.yml

**Review by beckermr — CHANGES_REQUESTED** [review]
Why did you remove references to circle? We still support it even if it is not used very much.

**Comment by croth1** [comment]
Hmh, oh I assumed it's not longer supported. I can keep it, but then I have to figure out how to fix the broken links to the CircleCI configuration 😬

**Comment by croth1** [comment]
So should be done now. Closes #1563.

**Comment by beckermr** [comment]
thank you!

**Pull request merged**
