### PR TITLE
Add minutes from May

### PR DESCRIPTION
**Pull request by jakirkham**
Adds the 2016-05-13 meeting minutes.

### CODE REVIEW

**Comment by jakirkham** [comment]
Adding the meeting notes from the build customization meeting and the general meeting. Please let me know if this looks alright to you. These are just the results from exporting the meeting notes from the Hackpad.

cc @msarahan @mingwandroid @kalefranz @mcg1969 @ukoethe @stuarteberg @pelson @mwiebe @jjhelmus @ericdill @scopatz @ocefpaf

**Comment by jakirkham** [comment]
If I don't hear any issues, this will be merged within a day.

**Comment by ericdill** [comment]
Why not just go ahead and merge?  If anyone needs a change, they can just submit a PR

**Comment by jakirkham** [comment]
Sure I would rather keep noise down on the commit history related to changes like this. Going back and tweaking the minutes should be slightly frowned upon.

Also, each merge will re-run the CI scripts, which can put us back in GitHub API throttling territory if we are not careful.

**Pull request merged**
