### PR TITLE
feedstock test local instructions

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks so much for doing this! I'll take a better look tomorrow but seems good!

**Comment by scopatz** [comment]
No problem!  Just trying to document everything that I find confusing or unintuitive :)

**Comment by shadowwalkersb** [comment]
This is all great! When are they going to be on the website?

**Comment by scopatz** [comment]
As soon as we get the website fixed. It seems like it might depend on pelson/conda-execute#36. See #287

**Comment by ocefpaf** [comment]
LGTM to you think we should add a not about the interactive use of the image?

**Comment by shadowwalkersb** [comment]
Are there additional steps to setup docker? Just installing docker and running the script didn't work for me.

**Comment by ocefpaf** [comment]
> Are there additional steps to setup docker? Just installing docker and running the script didn't work for me.

What was the error? Try pulling the image manually with:

```
docker pull condaforge/linux-anvil
```

**Comment by shadowwalkersb** [comment]
> What was the error?


```
docker: Error parsing reference: "HD/Users/some_path/repo-feedstock/recipe:/recipe_root" is not a valid repository/tag.
See 'docker run --help'.

```

**Comment by shadowwalkersb** [comment]
> Try pulling the image manually with:
> 
> docker pull condaforge/linux-anvil

Pulled the image manually. What's next? Running `ci_support/run_docker_build.sh` gives the same error.

**Comment by ocefpaf** [comment]
> Pulled the image manually. What's next? Running `ci_support/run_docker_build.sh` gives the same error.

Try the interactive approach then. The command

```
docker run -it --rm -v $(pwd):/home/ condaforge/linux-anvil /bin/sh
```

will get you inside the image and will mount your current directory at `home`. Navigate to the recipe and do a `conda build .`.

**Comment by shadowwalkersb** [comment]
Turns out I have a space in my path, `/Volumes/Mac HD/Users/some_path/repo-feedstock/recipe:/recipe_root`. Shell variables in the script need to be in double-quotes,
`${RECIPE_ROOT}` -> `"${RECIPE_ROOT}"`.

**Comment by scopatz** [comment]
@shadowwalkersb, I think that change needs to go in conda-smithy. There isn't much we can do about it here.

**Comment by shadowwalkersb** [comment]
Already done. Was just being lazy earlier. That means there is nothing wrong or missing with the instructions in this PR. 👍

**Comment by scopatz** [comment]
Awesome. So do we think this is good to merge then?

**Comment by shadowwalkersb** [comment]
How about mentioning interactive usage as @ocefpaf suggested? It is pretty obvious, but mentioning the dependency on Docker may be good.

**Comment by scopatz** [comment]
I would love to have that in the docs, but since that isn't my use case I probably shouldn't be the one to write it.  I'll happily merge someone else's, though.

**Comment by pelson** [comment]
Thanks @scopatz and thanks for the review folks.
Nice, incremental improvement. 👍

**Comment by scopatz** [comment]
Thanks! It looks like this is successfully making it to the website now!

**Pull request merged**
