### PR TITLE
Glossary

### PR DESCRIPTION
**Pull request by angeloobeta**
PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs`
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] Rearranged the **Glossary** terms in alphabetical order, added **CLI (Command Line Interface)** to the glossary terms

### CODE REVIEW

**Comment by angeloobeta** [comment]
Rearrange the **Glossary** part of the documentation in alphabetical order; added  **CLI** (command prompt Interface) to the terms in the **Glossary**

**Comment by ForgottenProgramme** [comment]
@angeloobeta 
Obeta, someone from core will soon review your PR. 

You seem to have invested a lot of time into this.
I just wanted to take a moment to appreciate your efforts in this PR. :) <3

**Review by beckermr — CHANGES_REQUESTED** [review]
Per the PR instructions you cannot edit the files in the docs directory.

**Comment by Aaishpra** [comment]
> @angeloobeta
> Obeta, someone from core will soon review your PR.
> 
> I'm afraid you have made the changes in the wrong subdirectory (/docs).
> **You will have to make changes in the /src subdirectory.**
> 
> You seem to have invested a lot of time into this.
> I just wanted to take a moment to appreciate your efforts in this PR. :) <3

This pretty much happens with every newcomer i guess, although there is information about making edits to the src instead of docs in the readme but i think there should be some information about not making changes to html files as they are auto-generated. Me and @prachi237 also ran through the same thing and were trying to make edits in html files😂
Just a suggestion what do you all think about it.
Cc: @beckermr @viniciusdc

**Comment by viniciusdc** [comment]
> > @angeloobeta
> > Obeta, someone from core will soon review your PR.
> > I'm afraid you have made the changes in the wrong subdirectory (/docs).
> > **You will have to make changes in the /src subdirectory.**
> > You seem to have invested a lot of time into this.
> > I just wanted to take a moment to appreciate your efforts in this PR. :) <3
> 
> This pretty much happens with every newcomer i guess, although there is information about making edits to the src instead of docs in the readme but i think there should be some information about not making changes to html files as they are auto-generated. Me and @prachi237 also ran through the same thing and were trying to make edits in html files
> Just a little suggestion to help beginners what do you all think about it.
> Cc: @beckermr @viniciusdc

Uhm, in the beginning definitely there wasn't much advice for that, but we actually updated the readme files and our docs with that information. The PR templates also have some advice about that, but I agree that it's still conflicting advice as for the new users it won't look natural (cause they don’t know initially that we automated it). So the only thing that comes in my mind was using a linter to test if the right conditions for the PR were met.

**Comment by prachi237** [comment]
> > @angeloobeta
> > Obeta, someone from core will soon review your PR.
> > I'm afraid you have made the changes in the wrong subdirectory (/docs).
> > **You will have to make changes in the /src subdirectory.**
> > You seem to have invested a lot of time into this.
> > I just wanted to take a moment to appreciate your efforts in this PR. :) <3
> 
> This pretty much happens with every newcomer i guess, although there is information about making edits to the src instead of docs in the readme but i think there should be some information about not making changes to html files as they are auto-generated. Me and @prachi237 also ran through the same thing and were trying to make edits in html files😂
> Just a little suggestion to help beginners what do you all think about it.
> Cc: @beckermr @viniciusdc

 That's true 😂 I had no idea earlier what this sphinx is all about and as a web developer it's not that amusing to think that we have to make edits in html files

**Comment by jaimergp** [comment]
Integrated in #2087. Thanks!

**Pull request closed without merging**
