### PR TITLE
CFEP Governance

### PR DESCRIPTION
**Pull request by scopatz**
@conda-forge/core
This PR falls under standard, please vote and/or comment on this PR.
This PR needs 75% (15 members) of core to vote yea to pass.
To vote please leave Approve (yea) or Request Changes (nay) reviews.
If you would like changes to the current language please leave a comment or push to this branch.
This vote cannot be closed before May 22nd, 2019.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge/core, please vote on this if you have not already. Thanks! 😄

**Comment by scopatz** [comment]
I cannot "approve" the PR, since I opened it, but I am in favor.

**Comment by ocefpaf** [comment]
We have 10 out of 15 approving votes and so far we got 0 :-1:.
We are missing 8 people that did not cast their vote yet.

If you see your name below, and you are not "checked," please vote!
Give us your :+1: or :-1: by approving/rejecting the PR.

If you do not wish to participate in this voting let us know so we can recompute the 75% quota we need for this to pass.

- [X] Anthony Scopatz, @scopatz
- [X] Mike Sarahan, @msarahan
- [X] Peter K. G. Williams, @pkgw
- [X] Marius van Niekerk, @mariusvniekerk
- [X] Filipe Pires Alvarenga Fernandes, @ocefpaf
- [X] Sophia Castellarin, @soapy1
- [X] Jonathan J. Helmus, @jjhelmus
- [X] Matt Craig, @mwcraig
- [X] Lori Burns, @loriab
- [X] John Kirkham, @jakirkham
- [ ] Marcel Bargull, @mbargull
- [ ] Eric Dill, @ericdill
- [ ] Phil Elson, @pelson
- [ ] Isuru Fernando, @isuruf
- [ ] Björn Grüning, @bgruening
- [ ] Min Ragan-Kelley, @minrk
- [ ] Christopher J. Wright, @CJ-Wright
- [ ] Patrick Snape, @patricksnape

**Comment by ocefpaf** [comment]
:tada: CFEP-09 passed!

**Comment by jakirkham** [comment]
Thanks all! Great to see this in. 😄 🎉

**Pull request merged**
