### PR TITLE
Added code block below each configuration step

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
PR Checklist:

- [X] make all edits to the docs in the `src` directory, not in `docs`
- [X] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [X] put any other relevant information below

### CODE REVIEW

**Comment by ocefpaf** [comment]
@ForgottenProgramme are you familiar with netfly? Someone mentioned to me that we can publish draft docs with it. Maybe that is something we should put on our radar for the future.

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
> @ForgottenProgramme are you familiar with netfly? Someone mentioned to me that we can publish draft docs with it. Maybe that is something we should put on our radar for the future.

Meaning this ( https://github.com/conda-forge/conda-forge.github.io/issues/691 ) or something else?

Also worth noting RTD has added PR builds with previews. Not sure if that would be of interest. We had supported RTD previously. So that's another option

**Comment by ForgottenProgramme** [comment]
@ocefpaf 
Hey, Filipe! I haven't used Netlify before but thanks for mentioning it. 

I found a useful blog related to the feature you mentioned. 
Here: https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

I think having this PR preview feature for conda-forge docs will be a good idea since it will make reviewing PRs easier and faster.

**Comment by ForgottenProgramme** [comment]
Hey, @jakirkham !

I just searched about Read The Docs too. 

Found this: https://blog.readthedocs.com/pull-request-builder-general-availability/

**Comment by ForgottenProgramme** [comment]
I am thinking of working on the Deploy Preview (Netlify) feature now. 

@beckermr , @jakirkham 
Could you give me some pointers on getting started?

**Pull request merged**
