### PR TITLE
WIP: Status page link

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a link to the status page.

### CODE REVIEW

**Comment by jakirkham** [comment]
So, I think this should work correctly, @pelson. Though I don't know if we want it to show up here or in this order. Please let me know your thoughts.

**Comment by jakirkham** [comment]
Thanks. Just tested and verified that it works correctly.

Though forgot we need to do this for the feedstock page. Will update that in a subsequent PR.

**Comment by pelson** [comment]
Would you mind also removing the badges from that page? I have been meaning to do it for months - but I always worry we are triggering a DoS like attack whenever somebody visits the page (because there are ~1000 calls to the 3 CI providers per page impression)...

**Comment by jakirkham** [comment]
No kidding. I just tried to open that page and it nearly froze my browser.

**Comment by jakirkham** [comment]
Both addressed in PR ( https://github.com/conda-forge/conda-forge.github.io/pull/212 ).

**Comment by jakirkham** [comment]
Kind of orthogonal, but I have been mulling around the idea of moving the feedstocks webpage, template, and the CI to generate it to the feedstocks repo. It is pretty silly we trigger a CI job to regenerate those every time we merge here given what we are merging (pinnings, minutes, general docs, etc.) which have nothing to do with the feedstocks. This PR demonstrates that doing that would be seemless from the webpage perspective. On the programming level, it gives us better separation of concerns. The one thing we have to figure out is what to do with these scripts.

**Comment by jakirkham** [comment]
Broke out the link in a separate PR ( https://github.com/conda-forge/conda-forge.github.io/pull/213 ) and went ahead with it as it was straightforward. Verified that it works correctly now that it is up.

Dropping the badges is pursued in PR ( https://github.com/conda-forge/conda-forge.github.io/pull/212 ) only. Please let me know if that is whether that is what you had in mind.

**Comment by pelson** [comment]
Thanks @jakirkham.

**Pull request merged**
