### PR TITLE
add myself to src/core.csv

### PR DESCRIPTION
**Pull request by h-vetinari**
I recently joined core, being able to merge this PR is the test/proof that I have the required rights now.

### CODE REVIEW

**Comment by h-vetinari** [comment]
I have no idea why the link check fails now, where it seems to have passed previously. A similar error appeared in https://github.com/sphinx-doc/sphinx/issues/9435, but should have been fixed long ago (CI is using latest sphinx 7.0.1).

**Comment by h-vetinari** [comment]
OK, @beckermr told me to "just merge it". Here goes! :)

**Comment by h-vetinari** [comment]
Even scary red colours can't stop me now 😎 
image

**Comment by jaimergp** [comment]
For the record I think the error comes from this line, should be more generic:

https://github.com/conda-forge/conda-forge.github.io/blob/6428374e4f90121b20fb40ce9e17815f410a3987/src/conf.py#L120

**Pull request merged**
