### PR TITLE
Improved the Governance file section and corrected a few incorrect lines 

### PR DESCRIPTION
**Pull request by prachi237**
PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs`
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

### CODE REVIEW

**Comment by prachi237** [comment]
@viniciusdc  @beckermr  please review this section

**Review by beckermr — CHANGES_REQUESTED** [review]
We cannot merge this PR. The language in this section is voted on by the core team and forms our governance documents. It cannot be changed without a vote.

**Comment by beckermr** [comment]
I am going to close this PR for now. Thank you for being involved!

**Comment by prachi237** [comment]
> We cannot merge this PR. The language in this section is voted on by the core team and forms our governance documents. It cannot be changed without a vote.

Ohh damn I didn't know that, thanks

**Comment by jakirkham** [comment]
All good. It's not something we would have expected others to know

Thanks again for all of the work you have been doing here 😄

**Comment by beckermr** [comment]
yup! sorry to be terse in my note! Thank you!

**Pull request closed without merging**
