### PR TITLE
Add build environment section to knowledge base.

### PR DESCRIPTION
**Pull request by cmeyer**
Lack of this tidbit of information led me astray for many hours -- so documenting it here for future reference for myself and others.

### CODE REVIEW

**Comment by jakirkham** [comment]
I think `host` is activated, but not `build`, which is just added to the `PATH`. Could be wrong about this though.

**Comment by isuruf** [comment]
`host` is first activated and then `build` is activated on top. For `outputs` neither is activated and there's a switch. This should be in conda-build docs.

**Comment by cmeyer** [comment]
In my tests, I had a strictly Python 3.6 build/host section and the environment always showed 3.7 (at least on Linux/Mac). I did `conda info` in my `build.sh` to determine this. And also did `"${PYTHON}" --version`. The former always showed 3.7; the latter always 3.6.

**Comment by isuruf** [comment]
Please open an issue in conda-build

**Comment by cmeyer** [comment]
I'm not sure I have enough knowledge about the problem to write an issue -- is the issue that the build or host environment is not activated when `build.sh` or `bld.bat` is run?

Either way, the knowledge base for conda-forge contains other information similar to this - so I'd like to make the case that this documentation should be applied here, at least for now.

As a side note, as a relative newcomer to conda-forge, it's confusing to have some documentation in conda-build and some in conda-forge.github.io.

**Comment by isuruf** [comment]
> is the issue that the build or host environment is not activated when build.sh or bld.bat is run?

Yes. This shouldn't happen and you haven't provided enough info for us to reproduce or debug this.

**Comment by jakirkham** [comment]
I’m not sure I follow `conda info` is reporting information about the `base` environment where `conda` is installed. How does that tell you the environment wasn’t activated?

**Comment by cmeyer** [comment]
I was assuming that `conda info` would give info about the current environment; but either way, the problem in my code was that CMake was finding that environment, not the one I needed with NumPy installed! Using $PYTHON works perfectly though. This isn't holding me up at the moment.

I just added a regular 'python --version' to `build.sh` and it gives me 3.6.10 -- so in this case it looks like it is the right version.

I'm looking at reproducing the CMake issue here... a few more minutes to go.

**Comment by jakirkham** [comment]
Yeah I’ve definitely run into my fair share of CMake detection logic that got confused. Agree configuring the CMake to build with explicit paths work well.

**Comment by cmeyer** [comment]
After more investigation... my CMake was using $CONDA_PREFIX to find Python.

On my local machine, $CONDA_PREFIX seems invalid. On the conda-forge Azure builds, it points to a Python environment, but not the right one.

So it seems maybe that $CONDA_PREFIX is not a valid environment variable during `build.sh`.

**Comment by jakirkham** [comment]
So there are some subtle differences between `conda` and `conda-build`. `conda` calls this `$CONDA_PREFIX`, but `conda-build` calls this `$PREFIX`.

**Comment by cmeyer** [comment]
So is this documentation wrong or am I missing something else?

[Environment variables set during the build process](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-that-affect-the-build-process)

**Comment by jakirkham** [comment]
It might be incorrect documentation or a bug in `conda-build`. Would come up with an minimal reproducible example (MRE) and then raise an issue with them sharing the MRE.

**Comment by cmeyer** [comment]
It looks like $CONDA_PREFIX comes from `conda info` on Mac/Azure:

https://github.com/conda/conda-build/blob/1c76172835eec45ebaf5a0fa17dace84dc4e3475/ci/azurepipelines/run_conda_forge_build_setup_osx#L44

... again, I'm not sure where to go from here. I'm ok with just dropping this issue unless someone thinks it's incorrect.  Maybe I need to change this documentation PR to include something about how to get the Python path for CMake and to avoid using $CONDA_PREFIX?

**Comment by cmeyer** [comment]
Ok, just read your other note. I'll follow up at conda-build.

**Comment by cmeyer** [comment]
I'd still like to have something here about integrating CMake. Can I reword this documentation section for this PR? Or should I just drop it?

**Comment by jakirkham** [comment]
We’ve been in need of some CMake guidance/build tips in the docs. It could make sense to have this. May want to drop the comments on activation though.

**Comment by cmeyer** [comment]
Closing this PR. Superseded by https://github.com/conda-forge/conda-forge.github.io/pull/1016.

**Pull request closed without merging**
