### PR TITLE
Add Citation file

### PR DESCRIPTION
**Pull request by BastianZim**
PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

This PR adds a citation file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

### CODE REVIEW

**Comment by BastianZim** [comment]
This is only a draft because of the following:

1. I'm not sure if this messes something up with the build process.
2. We can add more info outside the original entry. See here for a list of supported fields: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md
3. Is there a better repo for this?
4. It's possible to directly connect this to Zenodo: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by BastianZim** [comment]
@conda-forge/core any comments/suggestions?

**Comment by beckermr** [comment]
I think this is perfect. LGTM!

**Comment by BastianZim** [comment]
Ok, I've added some supplemental info and linted the recipe, should be good to go.

**Comment by BastianZim** [comment]
Thanks

**Pull request merged**
