### PR TITLE
Add docs about the webservice

### PR DESCRIPTION
**Pull request by isuruf**
Don't merge until https://github.com/conda-forge/conda-forge-webservices/pull/102 is in.

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, here are the docs

**Comment by ocefpaf** [comment]
This LGTM. I would add a link to you test PR (or another "clean" one b/c I messed that up :stuck_out_tongue_winking_eye:) so people can see it in action.

**Comment by jakirkham** [comment]
Docs look good. Agree with @ocefpaf about adding a link to your test PR.

**Comment by jakirkham** [comment]
Also might be good to link over from the re-rendering section over to the re-render command.

**Pull request merged**
