### PR TITLE
pin glpk

### PR DESCRIPTION
**Pull request by dougalsutherland**
Pin to 4.61|4.62, per [the tracker](https://abi-laboratory.pro/tracker/timeline/glpk/).

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/glpk

**Comment by jjhelmus** [comment]
LGTM

**Comment by dougalsutherland** [comment]
Would be 4.63 if https://github.com/conda-forge/glpk-feedstock/pull/21 merges; it's not backwards-compatible.

**Comment by jakirkham** [comment]
Thanks @dougalsutherland. We can bump to 4.63 afterwards.

**Pull request merged**
