### PR TITLE
[WIP] Adding Autotick bot docs to conda-forge main docs

### LINKED ISSUE #1460: Integrating the autotick bot docs with the conda-forge main docs
Autotick bot docs: https://regro.github.io/cf-scripts/#

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
Fixes #1460 

**maintainer documentation:**

- [X] possible keys for the conda-forge.yaml (https://conda-forge.org/docs/maintainer/conda_forge_yml.html#bot)
bot rerun labels
- [X] conda-forge admin commands for adding bot-rerun label (https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-rerun-bot)
- [ ] command for adding automerge (https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge)
- [ ] rules about when PRs come
a.  for versions, if three version PRs are open, no more will be made
b. bot detects versions only if using a src URL with a version jinja2 variable and the version is roughly compatible with semver
c. for ABI migrations, the bot will generate the migration PR only once the upstream package has been built
d. ABI migrations are closed once all of the PRs in the migration have been issued

The stuff for the migration yaml docs is a lot less complete.

**migration yaml docs:**

- [ ] some of the relevant keys are in the example here: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/example.exyaml - however this is not all of them
- [ ] there are extra keys we should add - the pyp37 migration has most of them: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/pypy37.yaml
a. paused: if True, the migration is not marked as done but no PRs will be issued and it will not appear on the status page. This is important for migrations you want to stop but are not merged into the innings. If these migrations were deleted, then any feedstocks that got them would be misconfigured if rerendered.
b. longterm: if True, this migration will show on the status page in a separate section. This key is used to highlight big migrations that we expect to a long time like python minor version bumps, cuda, etc.
c. pr_limit: indicates how many PRs a migration can generate per run of the bot. This can be used to slow or speed up certain migrations.

### CODE REVIEW

**Comment by ForgottenProgramme** [comment]
@viniciusdc

**Comment by ForgottenProgramme** [comment]
image

**Comment by viniciusdc** [comment]
Hi @ForgottenProgramme, some interesting bot's related issues can be found you Gitter if you want some examples of probematic situatuations. I will rea thru the sections description later on today and add some comments in there if needed. Thanks for oppening this PR!  Also don't forget to add the contact information list... eg. check most common response... comment on gitter, calll conda-forge team ...

**Comment by ForgottenProgramme** [comment]
@beckermr 

> command for adding automerge (https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge)

I find this section a little confusing.

**Comment by beckermr** [comment]
What's confusing? Happy to review a PR with any changes you have of course!

**Comment by ForgottenProgramme** [comment]
@beckermr 
Hey, Matt! :)

Please see this: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge 

This sentence:

>...will instruct the admin bot to open a PR enabling the automatic merging of passing PRs from the auto-tick bot.

I don't understand this --"enabling the automatic merging of passing PRs from the auto-tick bot"

Also the link mentioned in that section no more exists.

**Comment by beckermr** [comment]
Feel free to fix the link to point to point to the new docs here. 

That text just means the command will generate a PR that will enabled automerge.

**Comment by ForgottenProgramme** [comment]
> Feel free to fix the link to point to point to the new docs here.

Okay!
 
> That text just means the command will generate a PR that will enabled automerge.

So does this works the same as the following key:
 
```
bot:
automerge: true

```
?

**Comment by beckermr** [comment]
That command generates a PR on the feedstock with that change. You have to merge the pr. Feel free to try it out!

**Comment by ForgottenProgramme** [comment]
Ahh.. got it now! 
Thanks, Matt! :)

**Pull request closed without merging**
