### PR TITLE
Try 2 to close 139

### LINKED ISSUE #139: Feedstock Repo script failing
Running into an exception for the last 2 days in the `feedstocks_repo` build. This appears to be far enough into the script that none of us noticed. This can be seen in the [log]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/130691832#L233-L244 ) and down below.

```
Prefix: /home/travis/conda/tmp_envs/f5607ad6e1b89da01f30
Running command: ['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', './feedstocks_repo/feedstocks']
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py", line 91, in <module>
    contents = env.from_string(''.join(fh)).render()
  File "/home/travis/conda/tmp_envs/f5607ad6e1b89da01f30/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/travis/conda/tmp_envs/f5607ad6e1b89da01f30/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis/conda/tmp_envs/f5607ad6e1b89da01f30/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'get'
CalledProcessError: Command '['python', '/home/travis/build/conda-forge/conda-forge.github.io/scripts/update_teams.py', './feedstocks_repo/feedstocks']' returned non-zero exit status 1
```

cc @pelson

### PR DESCRIPTION
**Pull request by ericdill**
Closes #139

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @ericdill. Sorry didn't see your change when I made that PR. Let's go with this.

**Comment by ericdill** [comment]
Nope, you had the correct change... I'm not writing good code right now :disappointed:

**Comment by ericdill** [comment]
0/2 on this fix -_-

**Comment by jakirkham** [comment]
Nonesense, you had the big picture. The rest is just details.

**Comment by ericdill** [comment]
> Sorry didn't see your change when I made that PR

Pretty sure those PRs were submitted within 10 seconds of each other :-D

**Comment by jakirkham** [comment]
Yeah, it was pretty crazy.

**Comment by jakirkham** [comment]
So, now we are hitting the selector issue. Basically, we need to pin `conda-build` to 1.20.1. Do you want to take this one? 😉

**Pull request merged**
