### PR TITLE
Don't update teams 

### PR DESCRIPTION
**Pull request by isuruf**
This is done by a webservice now, so there's no need do this here where it doesn't scale.

### CODE REVIEW

**Comment by jakirkham** [comment]
This is good to go now, right?

**Comment by isuruf** [comment]
Yes

**Comment by jakirkham** [comment]
Should we delete the script too?

**Comment by jakirkham** [comment]
To be clear am meaning `scripts/update_teams.py`.

**Comment by isuruf** [comment]
It doesn't hurt to keep it there. There are some scripts in `scripts` that are not used in CI, but can be useful.

**Comment by jakirkham** [comment]
That's true.

**Comment by jakirkham** [comment]
Thanks @isuruf.

**Comment by jakirkham** [comment]
Partially addresses issue ( https://github.com/conda-forge/conda-forge.github.io/issues/214 ).

**Pull request merged**
