### PR TITLE
Add back noarch condition

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Oh is this needed again?

**Comment by scopatz** [comment]
LGTM!

**Comment by isuruf** [comment]
See @mbargull's explanation at https://github.com/conda/conda/issues/7713#issuecomment-417916810

`wheel` which comes lexicographically after is fine. `chardet` which comes lexicographically before is not

**Comment by jakirkham** [comment]
Should we then qualify this with the lexicographic point? Asking as we have made some Conda dependencies `noarch: python` so this may be confusing to people.

**Comment by mbargull** [comment]
> Oh is this needed again?

`conda` still doesn't handle `noarch: python` packages perfectly on Windows.
Ideally it would have some separate `conda-python-package-installer` (long name to indicate that I didn't think of any actual name) package that would contain the linked console-script `.exe`\* so `noarch: python` packages won't have that awkward implicit dependency on the `base` environment's `conda`.

<sub>\* (and, IMHO, handle the creation of the entrypoints as well as `.pyc` compilation etc. -- but that's for another discussion)</sub>

**Comment by mbargull** [comment]
> Should we then qualify this with the lexicographic point?

No, I don't think so. The lexicographical thing is only an implementation detail of `conda` but not something we should rely on.

**Comment by jakirkham** [comment]
So should we revert any `noarch: python` conversions made to Conda's dependencies?

**Comment by isuruf** [comment]
Dependencies like tqdm have been noarch for 3 months, so I don't think we should go back.

**Comment by isuruf** [comment]
Even defaults ship tqdm as noarch.

**Comment by jakirkham** [comment]
I guess my point is we have now added guidance here that doesn't align with what we are doing. It would be good to either improve the guidance or align with it. No strong feelings on which, but clarity for others would be good 🙂

**Comment by mbargull** [comment]
> Even defaults ship tqdm as noarch.

Haham, I'm not sure if that was intentional or not..

I can't guarantee that relying on lexicographic order works in every case, though. I'd have to look that up.

**Pull request merged**
