### PR TITLE
Updated numpy matrix suggestion

### PR DESCRIPTION
**Pull request by ocefpaf**
I was too optimistic that the would add older `numpy`s for Windows quickly :smile: 

I am adjusting this until that is rectified.

@isuruf can you take a quick look?

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kain88-de you've been an early adopter of this too :smile: 
Do you mind taking a look at the text and see if that is clear enough?

**Comment by msarahan** [comment]
1.9 is the oldest we're going to support.  I have 1.9 builds on the c3i_test channel as of this morning: https://anaconda.org/c3i_test/numpy/files

**Comment by ocefpaf** [comment]
Cool. That is already a big help.

Just curious, is the reason to not add 1.8 the [gzip patch](https://github.com/conda-forge/numpy-feedstock/blob/numpy18/recipe/meta.yaml#L12)?  Or are there other complications on Windows that does not make it worth it?

**Comment by msarahan** [comment]
I kept the gzip patch in 1.8, but wasn't sure if it was necessary in 1.9.  There are no patches applied in the conda-forge 1.9 recipe: https://github.com/conda-forge/numpy-feedstock/blob/numpy19/recipe/meta.yaml

**Comment by ocefpaf** [comment]
> but wasn't sure if it was necessary in 1.9.

No, it is not necessary. Only for 1.8. I guess that my question was not well formed.

The reason to not support numpy 1.8 was the patch (or patching in general to make it work with py35 and py36) or other reasons?

**Comment by msarahan** [comment]
Ah.  There were many patches required for 1.8.  Mostly all for VS2015.  I started to backport them, but it just wasn't worth the effort.

**Comment by msarahan** [comment]
PS: I would also rather have a single version than all this selector junk.  I could have had 1.8 for everything but win py3.5+, but I think 1.9 is good enough, and having just 1.9 is so much less headache.

**Comment by ocefpaf** [comment]
> Ah. There were many patches required for 1.8. Mostly all for VS2015. I started to backport them, but it just wasn't worth the effort.

Got it. I'll update the docs as soon as the new packages land on `defaults`. For some a minimum of `1.9` makes more sense every day :smile:

**Comment by ocefpaf** [comment]
> PS: I would also rather have a single version than all this selector junk. I could have had 1.8 for everything but win py3.5+, but I think 1.9 is good enough, and having just 1.9 is so much less headache.

You just missed the opportunity to advertise conda-build 3 :wink:

**Comment by msarahan** [comment]
Yeah, cb3 would be great for this actually.  Having the selector in just conda_build_config.yaml would make it feasible to support 1.8 and 1.9 more easily.  Meh...  Maybe I'll go back and build 1.8 too, now that you mention it.

**Comment by ChrisBarker-NOAA** [comment]
Looks like 1.9 was released three years ago -- I think we're good. :-)

-CHB

**Comment by kain88-de** [comment]
Looks good to me

**Comment by ocefpaf** [comment]
@msarahan please let me know when the Windows pkg for numpy 1.9 on Python 3.6 and 3.5 land on `defaults` so I can update this. In short term I guess we can live with:

```yaml
build:
  numpy 1.9.*
run:
  numpy >=1.9
```

A long term solution is to using `conda-build 3` and a `conda_build_config.yaml` to control that.

**Pull request merged**
