### PR TITLE
how to get help

### PR DESCRIPTION
**Pull request by ocefpaf**
Partially addresses https://github.com/conda-forge/conda-forge.github.io/issues/852

I don't really like what I wrote here and there are lots of room for improvements! Please, if possible, push suggestions and changes directly to this PR.

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Where do you see conda-forge.github.io fitting into this?

Good question! I could say I did not think about it but the truth is that at the back of my brain was just hoping to see it replaced by the mailing list :smile:

What do you suggest?

**Comment by CJ-Wright** [comment]
That works for me, the mailing list is not used that much at the moment.

**Comment by ocefpaf** [comment]
> the mailing list is not used that much at the moment.

Yeah. Not sure if that is b/c people are moving away from mailing lists or b/c we never advertised it properly.

**Comment by CJ-Wright** [comment]
Personally I have a slight preference for the GH issues, since they are easier to track (closed v open, labels, assignments, etc.)

**Comment by ocefpaf** [comment]
> Personally I have a slight preference for the GH issues, since they are easier to track (closed v open, labels, assignments, etc.)

Should we add `conda-forge.github.io` as a generic-long-threads thing then and place the mailing list as an less preferred alternative to that?

**Comment by CJ-Wright** [comment]
@conda-forge/core thoughts? I think this is ready for review.

**Comment by scopatz** [comment]
LGTM! Thanks!

**Comment by ocefpaf** [comment]
Thanks @isuruf!

**Pull request merged**
