### PR TITLE
links added to direct back to homepage

### PR DESCRIPTION
**Pull request by Aaishpra**
Fixes: #1292 

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs`
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

image

### CODE REVIEW

**Comment by Aaishpra** [comment]
@viniciusdc review required here.

**Review by beckermr — CHANGES_REQUESTED** [review]
We should have the actual logo be this link, not add extra text.

**Comment by viniciusdc** [comment]
> We should have the actual logo be this link, not add extra text.

If I remember correctly she tried to add but without success, so this PR is an alternative. But now that i digged more into it here is the docs for the sphinx theme we are currently using (see [here](https://github.com/conda-forge/conda-forge.github.io/blob/master/src/conf.py) for our usage) and [here](https://cloud-sptheme.readthedocs.io/en/latest/cloud_theme.html#usage) for the docs. YOu could try this option `logotarget` in [options](https://cloud-sptheme.readthedocs.io/en/latest/cloud_theme.html#structure) and test if it solves our problem

**Comment by Aaishpra** [comment]
hey @viniciusdc can you provide a correct route that directs back to the homepage actually `../index` or `.index` doesn't seem to work and the link I used in this PR `https://conda-forge.org` gives page not found as result.
I am using `logotarget` like this hope this is the correct way
image

**Comment by viniciusdc** [comment]
> hey @viniciusdc can you provide a correct route that directs back to the homepage actually `../index` or `.index` doesn't seem to work and the link I used in this PR `https://conda-forge.org` gives page not found as result.
> I am using `logotarget` like this hope this is the correct way
> image

What happened when you used `../index` ?

**Comment by beckermr** [comment]
Try the actual web address: `www.conda-forge.org`

**Comment by viniciusdc** [comment]
> Try the actual web address: `www.conda-forge.org`

yeah, thanks Matt but I was looking into that `logotarget` and it will probably only accept files as entries. To enable url too we might need to create a black inside `_templates`

**Comment by Aaishpra** [comment]
> What happened when you used `../index` ? Also try this `'../'` too

It shows me a blank page which says`Cannot GET /src/_build/index.html` for `../index` and `Cannot GET /src/_build/.html` for `../`

**Comment by Aaishpra** [comment]
Hey @viniciusdc @beckermr  I used `'logotarget': '../../../index'` and changed `index.html.tmpl` to `index.html` and it is working correctly now. I will send a new PR cuz this PR is a bit messy now .

**Pull request closed without merging**
